version: "3.8"

services:
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    user: "0"
    ports:
      - "3000:3000"
      - "3100:3100"
      - "3200:3200"
    env_file:
      - ./env/grafana.env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/loki-local-config.yaml:/etc/loki/local-config.yaml
      - ./grafana/config.alloy:/etc/alloy/config.alloy
    networks:
      - data-engineering

  alertmanager:
    depends_on:
      - grafana
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    networks:
      - data-engineering

  pyspark:
    depends_on:
      - alertmanager
    build:
      context: ./pyspark
      dockerfile: Dockerfile
    container_name: pyspark
    ports:
      - "8888:8888"     # Jupyter Lab
      - "4040:4040"     # Spark UI
      - "18080:18080"   # Spark History Server (optional)

    volumes:
      - ./scripts:/workspace
      - C:\Users\sonuf\.aws:/root/.aws

    environment:
      - SPARK_LOG_LEVEL=DEBUG
      - AWS_DEFAULT_REGION=ap-south-1
      - PYSPARK_PYTHON=/env/bin/python
    
    networks:
      - data-engineering

    working_dir: /workspace

    stdin_open: true
    tty: true

networks:
  data-engineering:
    driver: bridge

volumes:
  grafana_data: