USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE WAREHOUSE data_analytics_wh
WITH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Data Analytics Warehouse for BI and Data Analysis';

CREATE OR REPLACE RESOURCE MONITOR monthly_monitor_data_analytics
WITH
    CREDIT_QUOTA = 5
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
    ON 70 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE data_analytics_wh SET RESOURCE_MONITOR = monthly_monitor_data_analytics;

CREATE OR REPLACE WAREHOUSE data_engineer_wh
WITH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'ECONOMY'
    COMMENT = 'Data Engineering Warehouse for ETL and Data Processing';

CREATE OR REPLACE RESOURCE MONITOR monthly_monitor_data_engineering
WITH
    CREDIT_QUOTA = 50
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
    ON 70 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE data_engineer_wh SET RESOURCE_MONITOR = monthly_monitor_data_engineering;

CREATE OR REPLACE WAREHOUSE dba_wh
WITH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'ECONOMY'
    COMMENT = 'Data Engineering Warehouse for ETL and Data Processing';

CREATE OR REPLACE RESOURCE MONITOR monthly_monitor_dba
WITH
    CREDIT_QUOTA = 50
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
    ON 70 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE dba_wh SET RESOURCE_MONITOR = monthly_monitor_dba;

SHOW WAREHOUSES;