USE ROLE ACCOUNTADMIN;


-- DATA ANALYST ROLE GRANTS
GRANT ROLE data_analyst_role TO USER data_analyst;

-- GRANT USAGE ON DATABASE SNOWFLAKE_LEARNING_DB TO ROLE data_analyst_role;
ALTER USER data_analyst SET DEFAULT_WAREHOUSE = data_analytics_wh;

GRANT USAGE, OPERATE ON WAREHOUSE data_analytics_wh TO ROLE data_analyst_role;
GRANT MONITOR ON RESOURCE MONITOR monthly_monitor_data_analytics TO ROLE data_analyst_role;

-- DATA ENGINEER ROLE GRANTS
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE DATA_ENGINEER_ROLE;
GRANT VIEW LINEAGE ON ACCOUNT TO ROLE DATA_ENGINEER_ROLE;
GRANT ROLE data_engineer_role TO USER data_engineer;

-- GRANT ROLE data_engineer_role TO USER data_analyst;
-- REVOKE ROLE data_engineer_role FROM USER data_analyst;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE data_engineer_role;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DATA_ENGINEER_ROLE;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE DATA_ENGINEER_ROLE;
GRANT ROLE data_analyst_role, data_engineer_role, dba_role, prod_support_role TO USER sonufgh32;
SHOW GRANTS TO ROLE data_engineer_role;
ALTER USER data_engineer SET DEFAULT_WAREHOUSE = data_engineer_wh;
GRANT 
GRANT USAGE, OPERATE, MODIFY ON WAREHOUSE data_engineer_wh TO ROLE data_engineer_role;
GRANT MODIFY ON RESOURCE MONITOR monthly_monitor_data_engineering TO ROLE data_engineer_role;

ALTER USER data_engineer SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAokz2tQkFk7GNHQv2ClXH
NVdvYeZ84UcbmgjrcdkWEK0oNgbBnJafSB4vbKTstf6Xk+GEpCMle6V+Qt1F4JF3
xb0ArBpRyQJiOCT2q0iQLQzZAg+zfm4sv4pxLqvODSpBqQgiemxunFT2r2uwW+MG
G8zGQ3cp+vRt5tpsaiTihwMiqf6EsWpmOWGcX41LRDODsxTLUPBpkh+Cuf1M1AVw
FBkVX8prusOwMdQvJTyRsRMTZmeLA6jeLoBbfPZZWuufQANnPuHCimgAdMS4g0lX
6P8QrXoVEO/e5zKQpWTdAuSSOrGRpwIgezbmJJ21Yjya+sNWYUY9urm75nS/L70F
9QIDAQAB';

-- DATABASE ADMIN ROLE GRANTS
GRANT ROLE dba_role TO USER database_admin;
GRANT USAGE, OPERATE, MODIFY ON WAREHOUSE dba_wh TO ROLE DBA_ROLE;
GRANT MODIFY ON RESOURCE MONITOR monthly_monitor_dba TO ROLE DBA_ROLE;

-- PROD SUPPORT ROLE GRANTS
GRANT ROLE prod_support_role TO USER prod_support;

-- ETL SERVICE ROLE GRANTS
GRANT ROLE ETL_ROLE TO USER etl_service;


-- SHOW GRANTS
-- SHOW GRANTS ON DATABASE SNOWFLAKE_LEARNING_DB;
-- SHOW GRANTS ON SCHEMA SNOWFLAKE_LEARNING_DB.INFORMATION_SCHEMA;
-- SHOW GRANTS ON TABLE SNOWFLAKE_LEARNING_DB.INFORMATION_SCHEMA.APPLICABLE_ROLES;
