USE ROLE DATA_ENGINEER_ROLE;

DROP COMPUTE POOL IF EXISTS data_engineer_pool;
DROP COMPUTE POOL IF EXISTS data_analytics_pool;

-- Run below command if not able to drop compute pool
-- ALTER COMPUTE POOL DATA_ENGINEER_POOL STOP ALL;
-- ALTER COMPUTE POOL data_analytics_pool STOP ALL;
CREATE COMPUTE POOL data_engineer_pool
  MIN_NODES = 1
  MAX_NODES = 5
  INSTANCE_FAMILY = CPU_X64_S
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  AUTO_SUSPEND_SECS = 60;

ALTER COMPUTE POOL data_engineer_pool RESUME;

ALTER COMPUTE POOL data_engineer_pool SUSPEND;

CREATE COMPUTE POOL data_analytics_pool
  MIN_NODES = 1
  MAX_NODES = 3
  INSTANCE_FAMILY = CPU_X64_S
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  AUTO_SUSPEND_SECS = 60;

ALTER COMPUTE POOL data_analytics_pool RESUME;

ALTER COMPUTE POOL data_analytics_pool SUSPEND;

SHOW COMPUTE POOLS;
DESCRIBE COMPUTE POOL data_engineer_pool;