DROP DATABASE IF EXISTS ETL;

USE ROLE DATA_ENGINEER_ROLE;
USE WAREHOUSE DATA_ENGINEER_WH;

CREATE OR REPLACE DATABASE ETL;
CREATE OR REPLACE SCHEMA LANDING_ZONE;
CREATE OR REPLACE SCHEMA CURATED_ZONE;
CREATE OR REPLACE SCHEMA CONSUMPTION_ZONE;

SHOW SCHEMAS IN DATABASE ETL;

ALTER SESSION SET TIMEZONE = 'Asia/Kolkata';

CREATE OR REPLACE STORAGE INTEGRATION S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::741448939728:role/SnowflakeStageRole'
    STORAGE_ALLOWED_LOCATIONS = ('s3://shivchoudhury-datasets/snowflake/csv/', 's3://shivchoudhury-datasets/snowflake/json/')
    COMMENT = 'AWS S3 Connection.';

SHOW STORAGE INTEGRATIONS;

CREATE OR REPLACE FILE FORMAT ETL.LANDING_ZONE.ETL_CSV_FILE_FORMAT
    TYPE = 'csv'
    COMPRESSION = 'auto'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '\042'
    NULL_IF = ('\\N');

CREATE OR REPLACE TRANSIENT TABLE ETL.LANDING_ZONE.LANDING_ITEM(
    ITEM_ID STRING,
    ITEM_DESC STRING,
    START_DATE DATE,
    END_DATE DATE,
    PRICE NUMBER(7, 2),
    ITEM_CLASS STRING,
    ITEM_CATEGORY STRING
) COMMENT = 'This is item table within landing schema';

CREATE OR REPLACE TRANSIENT TABLE ETL.LANDING_ZONE.LANDING_CUSTOMER(
    CUSTOMER_ID STRING,
    SALUTATION STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    BIRTH_DAY STRING,
    BIRTH_MONTH STRING,
    BIRTH_YEAR STRING,
    BIRTH_COUNTRY STRING,
    EMAIL_ADDRESS STRING
) COMMENT = 'This is customer table within landing schema';

CREATE OR REPLACE TRANSIENT TABLE ETL.LANDING_ZONE.LANDING_ORDER(
    ORDER_DATE STRING,
    ORDER_TIME STRING,
    ITEM_ID STRING,
    ITEM_DESC STRING,
    CUSTOMER_ID STRING,
    SALUTATION STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    STORE_ID STRING,
    STORE_NAME STRING,
    ORDER_QUANTITY STRING,
    SALE_PRICE STRING,
    DISCOUNT_AMT STRING,
    COUPON_AMT STRING,
    NET_PAID STRING,
    NET_PAID_TAX STRING,
    NET_PROFIT STRING
) COMMENT = 'This is order table within landing schema';

SHOW TABLES IN SCHEMA LANDING_ZONE;

CREATE OR REPLACE STAGE ETL.LANDING_ZONE.DELTA_ITEM_STAGE
    URL = 's3://shivchoudhury-datasets/snowflake/csv/items/'
    STORAGE_INTEGRATION = S3_INTEGRATION
    COMMENT = 'Item Table Stage';

CREATE OR REPLACE STAGE ETL.LANDING_ZONE.DELTA_CUSTOMER_STAGE
    URL = 's3://shivchoudhury-datasets/snowflake/csv/customers/'
    STORAGE_INTEGRATION = S3_INTEGRATION
    COMMENT = 'Customer Table Stage';

CREATE OR REPLACE STAGE ETL.LANDING_ZONE.DELTA_ORDER_STAGE
    URL = 's3://shivchoudhury-datasets/snowflake/csv/orders/'
    STORAGE_INTEGRATION = S3_INTEGRATION
    COMMENT = 'Order Table Stage';

SHOW STAGES IN SCHEMA LANDING_ZONE;

LIST @ETL.LANDING_ZONE.DELTA_ITEM_STAGE;
LIST @ETL.LANDING_ZONE.DELTA_CUSTOMER_STAGE;
LIST @ETL.LANDING_ZONE.DELTA_ORDER_STAGE;

CREATE OR REPLACE PIPE ETL.LANDING_ZONE.ITEM_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO ETL.LANDING_ZONE.LANDING_ITEM
FROM
    @ETL.LANDING_ZONE.DELTA_ITEM_STAGE
    FILE_FORMAT = ETL.LANDING_ZONE.ETL_CSV_FILE_FORMAT
    PATTERN = '.*item.*[.]csv'
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE ETL.LANDING_ZONE.CUSTOMER_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO ETL.LANDING_ZONE.LANDING_CUSTOMER
FROM
    @ETL.LANDING_ZONE.DELTA_CUSTOMER_STAGE
    FILE_FORMAT = ETL.LANDING_ZONE.ETL_CSV_FILE_FORMAT
    PATTERN = '.*customer.*[.]csv'
    ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE ETL.LANDING_ZONE.ORDER_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO ETL.LANDING_ZONE.LANDING_ORDER
FROM
    @ETL.LANDING_ZONE.DELTA_ORDER_STAGE
    FILE_FORMAT = ETL.LANDING_ZONE.ETL_CSV_FILE_FORMAT
    PATTERN = '.*order.*[.]csv'
    ON_ERROR = 'CONTINUE';

SHOW PIPES IN SCHEMA LANDING_ZONE;

SELECT SYSTEM$PIPE_STATUS('ETL.LANDING_ZONE.ORDER_PIPE');
SELECT SYSTEM$PIPE_STATUS('ETL.LANDING_ZONE.ITEM_PIPE');
SELECT SYSTEM$PIPE_STATUS('ETL.LANDING_ZONE.CUSTOMER_PIPE');

CREATE OR REPLACE STREAM
    ETL.LANDING_ZONE.ITEM_STREAM
    ON TABLE ETL.LANDING_ZONE.LANDING_ITEM
    APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM
    ETL.LANDING_ZONE.CUSTOMER_STREAM
    ON TABLE ETL.LANDING_ZONE.LANDING_CUSTOMER
    APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM
    ETL.LANDING_ZONE.ORDER_STREAM
    ON TABLE ETL.LANDING_ZONE.LANDING_ORDER
    APPEND_ONLY = TRUE;

SHOW STREAMS IN SCHEMA LANDING_ZONE;
SELECT * FROM INFORMATION_SCHEMA.LOAD_HISTORY LIMIT 10;

ALTER PIPE ETL.LANDING_ZONE.ITEM_PIPE REFRESH;
SELECT COUNT(*) FROM ETL.LANDING_ZONE.LANDING_ITEM;

ALTER PIPE ETL.LANDING_ZONE.CUSTOMER_PIPE REFRESH;
SELECT COUNT(*) FROM ETL.LANDING_ZONE.LANDING_CUSTOMER;

ALTER PIPE ETL.LANDING_ZONE.ORDER_PIPE REFRESH;
SELECT COUNT(*) FROM ETL.LANDING_ZONE.LANDING_ORDER;

-- CURATED_ZONE

CREATE OR REPLACE TRANSIENT TABLE ETL.CURATED_ZONE.CURATED_ITEM(
    ITEM_PK NUMBER AUTOINCREMENT,
    ITEM_ID STRING,
    ITEM_DESC STRING,
    START_DATE DATE,
    END_DATE DATE,
    PRICE NUMBER(7, 2),
    ITEM_CLASS STRING,
    ITEM_CATEGORY STRING
) COMMENT = 'This is item table within curated schema';

CREATE OR REPLACE TRANSIENT TABLE ETL.CURATED_ZONE.CURATED_CUSTOMER(
    CUSTOMER_PK NUMBER AUTOINCREMENT,
    CUSTOMER_ID STRING,
    SALUTATION STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    BIRTH_DAY NUMBER,
    BIRTH_MONTH NUMBER,
    BIRTH_YEAR NUMBER,
    BIRTH_COUNTRY STRING,
    EMAIL_ADDRESS STRING
) COMMENT = 'This is customer table within curated schema';

CREATE OR REPLACE TRANSIENT TABLE ETL.CURATED_ZONE.CURATED_ORDER(
    ORDER_PK NUMBER AUTOINCREMENT,
    ORDER_DATE DATE,
    ORDER_TIME STRING,
    ITEM_ID STRING,
    ITEM_DESC STRING,
    CUSTOMER_ID STRING,
    SALUTATION STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    STORE_ID STRING,
    STORE_NAME STRING,
    ORDER_QUANTITY NUMBER,
    SALE_PRICE NUMBER(7, 2),
    DISCOUNT_AMT NUMBER(7, 2),
    COUPON_AMT NUMBER(7, 2),
    NET_PAID NUMBER(7, 2),
    NET_PAID_TAX NUMBER(7, 2),
    NET_PROFIT NUMBER(7, 2)
) COMMENT = 'This is order table within curated schema';

SHOW TABLES IN SCHEMA CURATED_ZONE;

-- INSERT INTO ETL.CURATED_ZONE.CURATED_ITEM(ITEM_ID, ITEM_DESC, START_DATE, END_DATE, PRICE, ITEM_CLASS, ITEM_CATEGORY)
-- SELECT ITEM_ID, ITEM_DESC, START_DATE, END_DATE, PRICE, ITEM_CLASS, ITEM_CATEGORY FROM ETL.LANDING_ZONE.LANDING_ITEM;
-- INSERT INTO ETL.CURATED_ZONE.CURATED_CUSTOMER(CUSTOMER_ID, SALUTATION, FIRST_NAME, LAST_NAME, BIRTH_DAY, BIRTH_MONTH, BIRTH_YEAR, BIRTH_COUNTRY, EMAIL_ADDRESS)
-- SELECT CUSTOMER_ID, SALUTATION, FIRST_NAME, LAST_NAME, BIRTH_DAY, BIRTH_MONTH, BIRTH_YEAR, BIRTH_COUNTRY, EMAIL_ADDRESS FROM ETL.LANDING_ZONE.LANDING_CUSTOMER;
-- INSERT INTO ETL.CURATED_ZONE.CURATED_ORDER(ORDER_DATE, ORDER_TIME, ITEM_ID, ITEM_DESC, CUSTOMER_ID, SALUTATION, FIRST_NAME, LAST_NAME, STORE_ID, STORE_NAME, ORDER_QUANTITY, SALE_PRICE, DISCOUNT_AMT, COUPON_AMT, NET_PAID, NET_PAID_TAX, NET_PROFIT)
-- SELECT ORDER_DATE, ORDER_TIME, ITEM_ID, ITEM_DESC, CUSTOMER_ID, SALUTATION, FIRST_NAME, LAST_NAME, STORE_ID, STORE_NAME, ORDER_QUANTITY, SALE_PRICE, DISCOUNT_AMT, COUPON_AMT, NET_PAID, NET_PAID_TAX, NET_PROFIT FROM ETL.LANDING_ZONE.LANDING_ORDER;

CREATE OR REPLACE TASK ETL.CURATED_ZONE.CURATED_ITEM_TASK
    WAREHOUSE = 'DATA_ENGINEER_WH'
    SCHEDULE = '3 Minute'
    WHEN SYSTEM$STREAM_HAS_DATA('ETL.LANDING_ZONE.ITEM_STREAM')
    AS
    MERGE INTO ETL.CURATED_ZONE.CURATED_ITEM CUR_ITEM USING ETL.LANDING_ZONE.ITEM_STREAM RAW_ITEM
    ON CUR_ITEM.ITEM_ID = RAW_ITEM.ITEM_ID
    AND CUR_ITEM.ITEM_DESC = RAW_ITEM.ITEM_DESC
    AND CUR_ITEM.START_DATE = RAW_ITEM.START_DATE
    WHEN MATCHED
        THEN UPDATE SET
            CUR_ITEM.END_DATE = RAW_ITEM.END_DATE,
            CUR_ITEM.PRICE = RAW_ITEM.PRICE,
            CUR_ITEM.ITEM_CLASS = RAW_ITEM.ITEM_CLASS,
            CUR_ITEM.ITEM_CATEGORY = RAW_ITEM.ITEM_CATEGORY
    WHEN NOT MATCHED
        THEN
            INSERT(ITEM_ID, ITEM_DESC, START_DATE, END_DATE, PRICE, ITEM_CLASS, ITEM_CATEGORY)
            VALUES(RAW_ITEM.ITEM_ID, RAW_ITEM.ITEM_DESC, RAW_ITEM.START_DATE, RAW_ITEM.END_DATE, RAW_ITEM.PRICE, RAW_ITEM.ITEM_CLASS, RAW_ITEM.ITEM_CATEGORY);

CREATE OR REPLACE TASK ETL.CURATED_ZONE.CURATED_CUSTOMER_TASK
    WAREHOUSE = 'DATA_ENGINEER_WH'
    SCHEDULE = '2 Minute'
    WHEN SYSTEM$STREAM_HAS_DATA('ETL.LANDING_ZONE.CUSTOMER_STREAM')
    AS
    MERGE INTO ETL.CURATED_ZONE.CURATED_CUSTOMER CUR_CUST USING ETL.LANDING_ZONE.CUSTOMER_STREAM RAW_CUST
    ON CUR_CUST.CUSTOMER_ID = RAW_CUST.CUSTOMER_ID
    WHEN MATCHED
        THEN UPDATE SET
            CUR_CUST.SALUTATION = RAW_CUST.SALUTATION,
            CUR_CUST.FIRST_NAME = RAW_CUST.FIRST_NAME,
            CUR_CUST.LAST_NAME = RAW_CUST.LAST_NAME,
            CUR_CUST.BIRTH_DAY = RAW_CUST.BIRTH_DAY,
            CUR_CUST.BIRTH_MONTH = RAW_CUST.BIRTH_MONTH,
            CUR_CUST.BIRTH_YEAR = RAW_CUST.BIRTH_YEAR,
            CUR_CUST.BIRTH_COUNTRY = RAW_CUST.BIRTH_COUNTRY,
            CUR_CUST.EMAIL_ADDRESS = RAW_CUST.EMAIL_ADDRESS
    WHEN NOT MATCHED
        THEN INSERT(
            CUSTOMER_ID,
            SALUTATION,
            FIRST_NAME,
            LAST_NAME,
            BIRTH_DAY,
            BIRTH_MONTH,
            BIRTH_YEAR,
            BIRTH_COUNTRY,
            EMAIL_ADDRESS
        )
        VALUES(
            RAW_CUST.CUSTOMER_ID,
            RAW_CUST.SALUTATION,
            RAW_CUST.FIRST_NAME,
            RAW_CUST.LAST_NAME,
            RAW_CUST.BIRTH_DAY,
            RAW_CUST.BIRTH_MONTH,
            RAW_CUST.BIRTH_YEAR,
            RAW_CUST.BIRTH_COUNTRY,
            RAW_CUST.EMAIL_ADDRESS
        );


CREATE OR REPLACE TASK ETL.CURATED_ZONE.CURATED_ORDER_TASK
    WAREHOUSE = 'DATA_ENGINEER_WH'
    SCHEDULE = '1 Minute'
    WHEN SYSTEM$STREAM_HAS_DATA('ETL.LANDING_ZONE.ORDER_STREAM')
    AS
    MERGE INTO ETL.CURATED_ZONE.CURATED_ORDER CUR_ORDER USING ETL.LANDING_ZONE.ORDER_STREAM RAW_ORDER
    ON CUR_ORDER.ORDER_DATE = RAW_ORDER.ORDER_DATE
    AND CUR_ORDER.ORDER_TIME = RAW_ORDER.ORDER_TIME
    AND CUR_ORDER.ITEM_ID = RAW_ORDER.ITEM_ID
    AND CUR_ORDER.ITEM_DESC = RAW_ORDER.ITEM_DESC
    WHEN MATCHED THEN
        UPDATE SET
            CUR_ORDER.CUSTOMER_ID = RAW_ORDER.CUSTOMER_ID,
            CUR_ORDER.SALUTATION = RAW_ORDER.SALUTATION,
            CUR_ORDER.FIRST_NAME = RAW_ORDER.FIRST_NAME,
            CUR_ORDER.LAST_NAME = RAW_ORDER.LAST_NAME,
            CUR_ORDER.STORE_ID = RAW_ORDER.STORE_ID,
            CUR_ORDER.STORE_NAME = RAW_ORDER.STORE_NAME,
            CUR_ORDER.ORDER_QUANTITY = RAW_ORDER.ORDER_QUANTITY,
            CUR_ORDER.SALE_PRICE = RAW_ORDER.SALE_PRICE,
            CUR_ORDER.DISCOUNT_AMT = RAW_ORDER.DISCOUNT_AMT,
            CUR_ORDER.COUPON_AMT = RAW_ORDER.COUPON_AMT,
            CUR_ORDER.NET_PAID = RAW_ORDER.NET_PAID,
            CUR_ORDER.NET_PAID_TAX = RAW_ORDER.NET_PAID_TAX,
            CUR_ORDER.NET_PROFIT = RAW_ORDER.NET_PROFIT
    
    WHEN NOT MATCHED THEN
        INSERT(
            ORDER_DATE,
            ORDER_TIME,
            ITEM_ID,
            ITEM_DESC,
            CUSTOMER_ID,
            SALUTATION,
            FIRST_NAME,
            LAST_NAME,
            STORE_ID,
            STORE_NAME,
            ORDER_QUANTITY,
            SALE_PRICE,
            DISCOUNT_AMT,
            COUPON_AMT,
            NET_PAID,
            NET_PAID_TAX,
            NET_PROFIT
        )
        VALUES(
            RAW_ORDER.ORDER_DATE,
            RAW_ORDER.ORDER_TIME,
            RAW_ORDER.ITEM_ID,
            RAW_ORDER.ITEM_DESC,
            RAW_ORDER.CUSTOMER_ID,
            RAW_ORDER.SALUTATION,
            RAW_ORDER.FIRST_NAME,
            RAW_ORDER.LAST_NAME,
            RAW_ORDER.STORE_ID,
            RAW_ORDER.STORE_NAME,
            RAW_ORDER.ORDER_QUANTITY,
            RAW_ORDER.SALE_PRICE,
            RAW_ORDER.DISCOUNT_AMT,
            RAW_ORDER.COUPON_AMT,
            RAW_ORDER.NET_PAID,
            RAW_ORDER.NET_PAID_TAX,
            RAW_ORDER.NET_PROFIT
        );

SHOW TASKS IN SCHEMA CURATED_ZONE;

ALTER TASK ETL.CURATED_ZONE.CURATED_ITEM_TASK RESUME;
ALTER TASK ETL.CURATED_ZONE.CURATED_CUSTOMER_TASK RESUME;
ALTER TASK ETL.CURATED_ZONE.CURATED_ORDER_TASK RESUME;

SELECT COUNT(1) FROM ETL.CURATED_ZONE.CURATED_ITEM;
SELECT COUNT(1) FROM ETL.CURATED_ZONE.CURATED_CUSTOMER;
SELECT COUNT(1) FROM ETL.CURATED_ZONE.CURATED_ORDER;


SELECT * FROM ETL.LANDING_ZONE.ORDER_STREAM;
SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'CURATED_ORDER_TASK' ORDER BY SCHEDULED_TIME DESC;
SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'CURATED_CUSTOMER_TASK' ORDER BY SCHEDULED_TIME DESC;
SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'CURATED_ITEM_TASK' ORDER BY SCHEDULED_TIME DESC;

CREATE OR REPLACE STREAM ETL.CURATED_ZONE.CUR_ITEM_STREAM
ON TABLE ETL.CURATED_ZONE.CURATED_ITEM;
CREATE OR REPLACE STREAM ETL.CURATED_ZONE.CUR_CUSTOMER_STREAM
ON TABLE ETL.CURATED_ZONE.CURATED_CUSTOMER;
CREATE OR REPLACE STREAM ETL.CURATED_ZONE.CUR_ORDER_STREAM
ON TABLE ETL.CURATED_ZONE.CURATED_ORDER;

SHOW STREAMS IN SCHEMA ETL.CURATED_ZONE;

-- CONSUMPTION_ZONE
CREATE OR REPLACE TABLE ITEM_DIM(
    ITEM_DIM_KEY NUMBER AUTOINCREMENT,
    ITEM_ID STRING,
    ITEM_DESC STRING,
    START_DATE DATE,
    END_DATE DATE,
    PRICE NUMBER(7, 2),
    ITEM_CLASS STRING,
    ITEM_CATEGORY STRING,
    ADDED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    ACTIVE_FLAG VARCHAR(1) DEFAULT 'Y'
) COMMENT = 'This is item table within consumption schema';

CREATE OR REPLACE TABLE CUSTOMER_DIM(
    CUSTOMER_DIM_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID STRING,
    SALUTATION STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    BIRTH_DAY NUMBER,
    BIRTH_MONTH NUMBER,
    BIRTH_YEAR NUMBER,
    BIRTH_COUNTRY STRING,
    EMAIL_ADDRESS STRING,
    ADDED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    ACTIVE_FLAG VARCHAR(1) DEFAULT 'Y'
) COMMENT = 'This is customer table within consumption schema';

CREATE OR REPLACE TABLE ORDER_FACT(
    ORDER_FACT_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_DIM_KEY NUMBER,
    ITEM_DIM_KEY NUMBER,
    ORDER_DATE DATE,
    ORDER_COUNT NUMBER,
    ORDER_QUANTITY NUMBER,
    SALE_PRICE NUMBER(20, 2),
    DISCOUNT_AMT NUMBER(20, 2),
    COUPON_AMT NUMBER(20, 2),
    NET_PAID NUMBER(20, 2),
    NET_PAID_TAX NUMBER(20, 2),
    NET_PROFIT NUMBER(20, 2)
) COMMENT = 'This is order table within consumption schema';

SHOW TABLES IN SCHEMA CONSUMPTION_ZONE;

-- INSERT INTO ITEM_DIM(ITEM_ID, ITEM_DESC, START_DATE, END_DATE, PRICE, ITEM_CLASS, ITEM_CATEGORY)
-- SELECT ITEM_ID, ITEM_DESC, START_DATE, END_DATE, PRICE, ITEM_CLASS, ITEM_CATEGORY FROM CURATED_ZONE.CURATED_ITEM;
-- INSERT INTO CUSTOMER_DIM(CUSTOMER_ID, SALUTATION, FIRST_NAME, LAST_NAME, BIRTH_DAY, BIRTH_MONTH, BIRTH_YEAR, BIRTH_COUNTRY, EMAIL_ADDRESS)
-- SELECT CUSTOMER_ID, SALUTATION, FIRST_NAME, LAST_NAME, BIRTH_DAY, BIRTH_MONTH, BIRTH_YEAR, BIRTH_COUNTRY, EMAIL_ADDRESS FROM CURATED_ZONE.CURATED_CUSTOMER;
-- INSERT INTO ORDER_FACT(ORDER_DATE, CUSTOMER_DIM_KEY, ITEM_DIM_KEY, ORDER_COUNT, ORDER_QUANTITY, SALES_PRICE, DISCOUNT_AMT, COUPON_AMT, NET_PAID, NET_PAID_TAX, NET_PROFIT)
-- SELECT
--     CO.ORDER_DATE,
--     CD.CUSTOMER_DIM_KEY,
--     ID.ITEM_DIM_KEY,
--     COUNT(1) AS ORDER_COUNT,
--     SUM(CO.ORDER_QUANTITY),
--     SUM(CO.SALE_PRICE),
--     SUM(CO.DISCOUNT_AMT),
--     SUM(CO.COUPON_AMT),
--     SUM(CO.NET_PAID),
--     SUM(CO.NET_PAID_TAX),
--     SUM(CO.NET_PROFIT)
-- FROM
--     CURATED_ZONE.CURATED_ORDER CO
--     JOIN CONSUMPTION_ZONE.CUSTOMER_DIM CD ON CD.CUSTOMER_ID = CO.CUSTOMER_ID
--     JOIN CONSUMPTION_ZONE.ITEM_DIM ID ON ID.ITEM_ID = CO.ITEM_ID AND ID.ITEM_DESC = CO.ITEM_DESC AND ID.END_DATE IS NULL
--     GROUP BY CO.ORDER_DATE, CD.CUSTOMER_DIM_KEY, ID.ITEM_DIM_KEY ORDER BY CO.ORDER_DATE;

CREATE OR REPLACE TASK ETL.CONSUMPTION_ZONE.ITEM_CONSUMPTION_TASK
    WAREHOUSE = 'DATA_ENGINEER_WH'
    SCHEDULE = '4 Minute'
    WHEN SYSTEM$STREAM_HAS_DATA('ETL.CURATED_ZONE.CUR_ITEM_STREAM')
    AS
    MERGE INTO ETL.CONSUMPTION_ZONE.ITEM_DIM ITEM USING ETL.CURATED_ZONE.CUR_ITEM_STREAM ITEM_STREAM
    ON ITEM.ITEM_ID = ITEM_STREAM.ITEM_ID
    AND ITEM.START_DATE = ITEM_STREAM.START_DATE
    AND ITEM.ITEM_DESC = ITEM_STREAM.ITEM_DESC
    WHEN MATCHED
        AND ITEM_STREAM.METADATA$ACTION = 'INSERT'
        AND ITEM_STREAM.METADATA$ISUPDATE = 'TRUE' THEN
        UPDATE SET
            ITEM.END_DATE = ITEM_STREAM.END_DATE,
            ITEM.PRICE = ITEM_STREAM.PRICE,
            ITEM.ITEM_CLASS = ITEM_STREAM.ITEM_CLASS,
            ITEM.ITEM_CATEGORY = ITEM_STREAM.ITEM_CATEGORY
    
    WHEN MATCHED
        AND ITEM_STREAM.METADATA$ACTION = 'DELETE'
        AND ITEM_STREAM.METADATA$ISUPDATE = 'FALSE' THEN
        UPDATE
        SET
            ITEM.ACTIVE_FLAG = 'N',
            UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()
    
    WHEN NOT MATCHED
        AND ITEM_STREAM.METADATA$ACTION = 'INSERT'
        AND ITEM_STREAM.METADATA$ISUPDATE = 'FALSE' THEN
        INSERT(
            ITEM_ID,
            ITEM_DESC,
            START_DATE,
            END_DATE,
            PRICE,
            ITEM_CLASS,
            ITEM_CATEGORY
        )
        VALUES(
            ITEM_STREAM.ITEM_ID,
            ITEM_STREAM.ITEM_DESC,
            ITEM_STREAM.START_DATE,
            ITEM_STREAM.END_DATE,
            ITEM_STREAM.PRICE,
            ITEM_STREAM.ITEM_CLASS,
            ITEM_STREAM.ITEM_CATEGORY
        );


CREATE OR REPLACE TASK ETL.CONSUMPTION_ZONE.CUSTOMER_CONSUMPTION_TASK
    WAREHOUSE = 'DATA_ENGINEER_WH'
    SCHEDULE = '5 Minute'
    WHEN SYSTEM$STREAM_HAS_DATA('ETL.CURATED_ZONE.CUR_CUSTOMER_STREAM')
    AS
    MERGE INTO ETL.CONSUMPTION_ZONE.CUSTOMER_DIM CUST USING ETL.CURATED_ZONE.CUR_CUSTOMER_STREAM CUST_STREAM
    ON CUST.CUSTOMER_ID = CUST_STREAM.CUSTOMER_ID
    WHEN MATCHED
        AND CUST_STREAM.METADATA$ACTION = 'INSERT'
        AND CUST_STREAM.METADATA$ISUPDATE = 'TRUE' THEN
        UPDATE SET
            CUST.SALUTATION = CUST_STREAM.SALUTATION,
            CUST.FIRST_NAME = CUST_STREAM.FIRST_NAME,
            CUST.LAST_NAME = CUST_STREAM.LAST_NAME,
            CUST.BIRTH_DAY = CUST_STREAM.BIRTH_DAY,
            CUST.BIRTH_MONTH = CUST_STREAM.BIRTH_MONTH,
            CUST.BIRTH_YEAR = CUST_STREAM.BIRTH_YEAR,
            CUST.BIRTH_COUNTRY = CUST_STREAM.BIRTH_COUNTRY,
            CUST.EMAIL_ADDRESS = CUST_STREAM.EMAIL_ADDRESS
    WHEN MATCHED
        AND CUST_STREAM.METADATA$ACTION = 'DELETE'
        AND CUST_STREAM.METADATA$ISUPDATE = 'FALSE' THEN
        UPDATE SET
            CUST.ACTIVE_FLAG = 'N',
            CUST.UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()
    
    WHEN NOT MATCHED
        AND CUST_STREAM.METADATA$ACTION = 'INSERT'
        AND CUST_STREAM.METADATA$ISUPDATE = 'FALSE' THEN
        INSERT(
            CUSTOMER_ID,
            SALUTATION,
            FIRST_NAME,
            LAST_NAME,
            BIRTH_DAY,
            BIRTH_MONTH,
            BIRTH_YEAR,
            BIRTH_COUNTRY,
            EMAIL_ADDRESS
        )
        VALUES(
            CUST_STREAM.CUSTOMER_ID,
            CUST_STREAM.SALUTATION,
            CUST_STREAM.FIRST_NAME,
            CUST_STREAM.LAST_NAME,
            CUST_STREAM.BIRTH_DAY,
            CUST_STREAM.BIRTH_MONTH,
            CUST_STREAM.BIRTH_YEAR,
            CUST_STREAM.BIRTH_COUNTRY,
            CUST_STREAM.EMAIL_ADDRESS
        );

CREATE OR REPLACE TASK ETL.CONSUMPTION_ZONE.ORDER_CONSUMPTION_TASK
    WAREHOUSE = 'DATA_ENGINEER_WH' SCHEDULE = '6 Minute'
    WHEN SYSTEM$STREAM_HAS_DATA('ETL.CURATED_ZONE.CUR_ORDER_STREAM') AS
    INSERT OVERWRITE INTO ETL.CONSUMPTION_ZONE.ORDER_FACT(
        ORDER_DATE,
        CUSTOMER_DIM_KEY,
        ITEM_DIM_KEY,
        ORDER_COUNT,
        ORDER_QUANTITY,
        SALE_PRICE,
        DISCOUNT_AMT,
        COUPON_AMT,
        NET_PAID,
        NET_PAID_TAX,
        NET_PROFIT
    )
    SELECT
        CO.ORDER_DATE,
        CD.CUSTOMER_DIM_KEY,
        ID.ITEM_DIM_KEY,
        COUNT(1) AS ORDER_COUNT,
        SUM(CO.ORDER_QUANTITY),
        SUM(CO.SALE_PRICE),
        SUM(CO.DISCOUNT_AMT),
        SUM(CO.COUPON_AMT),
        SUM(CO.NET_PAID),
        SUM(CO.NET_PAID_TAX),
        SUM(CO.NET_PROFIT)
    FROM
        CURATED_ZONE.CURATED_ORDER CO
        JOIN CONSUMPTION_ZONE.CUSTOMER_DIM CD ON CD.CUSTOMER_ID = CO.CUSTOMER_ID
        JOIN CONSUMPTION_ZONE.ITEM_DIM ID ON ID.ITEM_ID = CO.ITEM_ID
        AND ID.ITEM_DESC = CO.ITEM_DESC
        AND ID.END_DATE IS NOT NULL
    GROUP BY
        CO.ORDER_DATE,
        CD.CUSTOMER_DIM_KEY,
        ID.ITEM_DIM_KEY
    ORDER BY CO.ORDER_DATE;



ALTER TASK ETL.CONSUMPTION_ZONE.ITEM_CONSUMPTION_TASK RESUME;
ALTER TASK ETL.CONSUMPTION_ZONE.CUSTOMER_CONSUMPTION_TASK RESUME;
ALTER TASK ETL.CONSUMPTION_ZONE.ORDER_CONSUMPTION_TASK RESUME;

SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY()) WHERE NAME = 'ORDER_CONSUMPTION_TASK' ORDER BY SCHEDULED_TIME DESC;


SELECT count(1) FROM ETL.CONSUMPTION_ZONE.ORDER_FACT;
SELECT count(1) FROM ETL.CONSUMPTION_ZONE.ITEM_DIM;
SELECT count(1) FROM ETL.CONSUMPTION_ZONE.CUSTOMER_DIM;

SELECT * FROM ETL.CONSUMPTION_ZONE.ORDER_FACT;
SELECT * FROM ETL.CONSUMPTION_ZONE.ITEM_DIM;
SELECT * FROM ETL.CONSUMPTION_ZONE.CUSTOMER_DIM;

DROP DATABASE ETL;