CREATE USER data_analyst
PASSWORD = 'data_analyst@1234'
FIRST_NAME = 'Shiv Ram'
LAST_NAME = 'Choudhury'
EMAIL = 'choudhuryshivram@gmail.com'
DEFAULT_WAREHOUSE = COMPUTE_WH
DEFAULT_NAMESPACE = MY_DB.PUBLIC
DEFAULT_ROLE = ANALYST_ROLE
MUST_CHANGE_PASSWORD = TRUE;

CREATE USER data_engineer
PASSWORD = 'data_engineer@1234'
FIRST_NAME = 'Shiv Ram'
LAST_NAME = 'Choudhury'
EMAIL = 'choudhuryshivram@gmail.com'
DEFAULT_WAREHOUSE = COMPUTE_WH
DEFAULT_NAMESPACE = MY_DB.PUBLIC
DEFAULT_ROLE = ANALYST_ROLE
MUST_CHANGE_PASSWORD = TRUE;

CREATE USER database_admin
PASSWORD = 'database_admin@1234'
FIRST_NAME = 'Shiv Ram'
LAST_NAME = 'Choudhury'
EMAIL = 'choudhuryshivram@gmail.com'
DEFAULT_WAREHOUSE = COMPUTE_WH
DEFAULT_NAMESPACE = MY_DB.PUBLIC
DEFAULT_ROLE = ANALYST_ROLE
MUST_CHANGE_PASSWORD = TRUE;

CREATE USER prod_support
PASSWORD = 'prod_support@1234'
FIRST_NAME = 'Shiv Ram'
LAST_NAME = 'Choudhury'
EMAIL = 'choudhuryshivram@gmail.com'
DEFAULT_WAREHOUSE = COMPUTE_WH
DEFAULT_NAMESPACE = MY_DB.PUBLIC
DEFAULT_ROLE = ANALYST_ROLE
MUST_CHANGE_PASSWORD = TRUE;