CREATE OR REPLACE WAREHOUSE data_analytics_wh
WITH
WAREHOUSE_SIZE = 'MEDIUM'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 2
SCALING_POLICY = 'STANDARD'
COMMENT = 'Data Analytics Warehouse for BI and Data Analysis';

CREATE RESOURCE MONITOR monthly_monitor
WITH
CREDIT_QUOTA = 10
FREQUENCY = MONTHLY
START_TIMESTAMP = IMMEDIATELY
TRIGGERS
ON 70 PERCENT DO NOTIFY
ON 90 PERCENT DO SUSPEND
ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE data_analytics_wh SET RESOURCE_MONITOR = monthly_monitor;

GRANT USAGE, OPERATE ON WAREHOUSE data_analytics_wh TO ROLE data_analyst_role;