-- create table bricks (
--   brick_id integer,
--   colour   varchar2(10),
--   shape    varchar2(10),
--   weight   integer
-- );

-- insert into bricks values ( 1, 'blue', 'cube', 1);
-- insert into bricks values ( 2, 'blue', 'pyramid', 2);
-- insert into bricks values ( 3, 'red', 'cube', 1);
-- insert into bricks values ( 4, 'red', 'cube', 2);
-- insert into bricks values ( 5, 'red', 'pyramid', 3);
-- insert into bricks values ( 6, 'green', 'pyramid', 1);

-- commit;

SELECT * FROM BRICKS;

SELECT COUNT(*) FROM BRICKS;

SELECT COUNT(1) OVER() AS TOTAL_COUNT FROM BRICKS;

SELECT B.*, COUNT(1) OVER() AS TOTAL_COUNT FROM BRICKS B;

SELECT B.*, COUNT(1) OVER(ORDER BY BRICK_ID) AS TOTAL_COUNT FROM BRICKS B;

SELECT B.*, COUNT(1) OVER(ORDER BY COLOUR) AS TOTAL_COUNT FROM BRICKS B;

SELECT
    B.*,
    ROW_NUMBER() OVER(PARTITION BY COLOUR ORDER BY SHAPE) AS RN,
    RANK() OVER(PARTITION BY COLOUR ORDER BY SHAPE) AS RANK,
    DENSE_RANK() OVER(PARTITION BY COLOUR ORDER BY SHAPE) AS DENSE_RANK
FROM
    BRICKS B;


-- Note: In some databases rank() / dense_rank() with over() return 1 for each rows

SELECT
    DISTINCT WEIGHT,
    COUNT(*) OVER(PARTITION by WEIGHT) AS WEIGHT_COUNT
FROM
    BRICKS b ORDER BY WEIGHT DESC;

SELECT COLOUR, COUNT(1), SUM(weight) FROM BRICKS GROUP BY COLOUR;

SELECT
    B.*,
    COUNT(*) OVER(PARTITION BY COLOUR) COUNT_PER_COLOUR,
    SUM(WEIGHT) OVER(PARTITION BY COLOUR) WEIGHT_PER_COLOUR
FROM BRICKS B;

SELECT
    B.*,
    COUNT(*) OVER(PARTITION BY SHAPE) BRICKS_PER_SHAPE,
    MEDIAN(WEIGHT) OVER(PARTITION BY SHAPE) MEDIAN_WEIGHT_PER_SHAPE
FROM
    BRICKS B
    ORDER BY SHAPE, WEIGHT, BRICK_ID;

SELECT
    B.*,
    COUNT(*) OVER(ORDER BY BRICK_ID) RUNNING_TOTAL,
    SUM(WEIGHT) OVER(ORDER BY BRICK_ID) RUNNING_WEIGHT
FROM BRICKS B;

SELECT
    B.BRICK_ID,
    B.WEIGHT,
    ROUND(AVG(WEIGHT) OVER(ORDER BY BRICK_ID), 2) AS AVERAGE_RUNNING_WEIGHT
FROM BRICKS B;

SELECT
    B.*,
    COUNT(*) OVER(PARTITION BY COLOUR ORDER BY BRICK_ID) RUNNING_TOTAL,
    SUM(WEIGHT) OVER(PARTITION BY COLOUR ORDER BY BRICK_ID) RUNNING_WEIGHT
FROM BRICKS B;

SELECT
    B.*,
    FIRST_VALUE(WEIGHT) OVER(ORDER BY BRICK_ID) AS FIRST_WEIGHT_BY_ID,
    LAST_VALUE(WEIGHT) OVER(ORDER BY BRICK_ID) AS LAST_WEIGHT_BY_ID
FROM BRICKS B;

SELECT
    B.*,
    FIRST_VALUE(WEIGHT) OVER(PARTITION BY SHAPE) AS FIRST_WEIGHT_SHAPE_PARTITION,
    LAST_VALUE(WEIGHT) OVER(PARTITION BY SHAPE) AS LAST_WEIGHT_SHAPE_PARTITION,
    NTH_VALUE(WEIGHT, 2) OVER(PARTITION BY SHAPE ORDER BY COLOUR) AS NTH_WEIGHT_SHAPE_PARTITION
FROM BRICKS B;

SELECT
    B.*,
    FIRST_VALUE(WEIGHT) OVER(PARTITION BY SHAPE ORDER BY BRICK_ID) AS FIRST_WEIGHT_SHAPE_PARTITION,
    LAST_VALUE(WEIGHT) OVER(PARTITION BY SHAPE ORDER BY BRICK_ID) AS LAST_WEIGHT_SHAPE_PARTITION -- RUNNING VALUES
FROM BRICKS B;

SELECT
    B.*,
    LAG(SHAPE) OVER(ORDER BY BRICK_ID) PREV_SHAPE,
    LEAD(SHAPE) OVER(ORDER BY BRICK_ID) NEXT_SHAPE
FROM BRICKS B;

SELECT
    B.*,
    NVL(LAG(SHAPE) OVER(ORDER BY BRICK_ID), SHAPE) PREV_SHAPE,
    NVL(LEAD(SHAPE) OVER(ORDER BY BRICK_ID), SHAPE) NEXT_SHAPE
FROM BRICKS B;

-- FILTERING FUNCTIONS

SELECT
    COLOUR
FROM BRICKS
GROUP BY COLOUR
HAVING COUNT(*) >= 2;

-- SELECT COLOUR FROM BRICKS WHERE COUNT(*) OVER(PARTITION BY COLOUR) >= 2;
-- RESULT IN ERROR AS WE CAN'T USE THIS FUNCTION WITH WHERE CLAUSE

SELECT
    *
FROM (
    SELECT
        B.*,
        COUNT(*) OVER(PARTITION BY COLOUR) COLOUR_COUNT
    FROM BRICKS B
)
WHERE COLOUR_COUNT >= 2;

WITH TOTALS AS (
    SELECT
        B.*,
        SUM(WEIGHT) OVER(
            PARTITION BY SHAPE
        ) WEIGHT_PER_SHAPE,
        SUM(WEIGHT) OVER(
            PARTITION BY SHAPE
            ORDER BY BRICK_ID
        ) RUNNING_WEIGHT_BY_ID
    FROM BRICKS B
)
SELECT
    *
FROM TOTALS
WHERE
    WEIGHT_PER_SHAPE > 4
    AND RUNNING_WEIGHT_BY_ID > 4
ORDER BY BRICK_ID;

SELECT
    B.*,
    COUNT(*) OVER(
        ORDER BY WEIGHT
    ) AS RUNNING_TOTAL,
    SUM(WEIGHT) OVER(
        ORDER BY WEIGHT
    ) RUNNING_WEIGHT
FROM
    BRICKS B
ORDER BY WEIGHT;

SELECT
    B.*,
    COUNT(*) OVER(
        ORDER BY WEIGHT
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) RUNNING_TOTAL,
    SUM(WEIGHT) OVER(
        ORDER BY WEIGHT
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) RUNNING_WEIGHT
FROM
    BRICKS B
ORDER BY WEIGHT;

SELECT
    B.*,
    COUNT(*) OVER(
        ORDER BY WEIGHT, BRICK_ID
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) RUNNING_TOTAL,
    SUM(WEIGHT) OVER(
        ORDER BY WEIGHT, BRICK_ID
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) RUNNING_WEIGHT
FROM
    BRICKS B
ORDER BY WEIGHT, BRICK_ID;

SELECT
    B.*,
    SUM(WEIGHT) OVER(
        ORDER BY WEIGHT
        ROWS BETWEEN 1 PRECEDING AND CURRENT ROW
    ) RUNNING_ROW_WEIGHT,
    SUM(WEIGHT) OVER(
        ORDER BY WEIGHT
        RANGE BETWEEN 1 PRECEDING AND CURRENT ROW
    ) RUNNING_VALUE_WEIGHT
FROM
    BRICKS B 
ORDER BY WEIGHT, BRICK_ID;