SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT COUNT(*) FROM EMP HAVING COUNT(*) > 14;

SELECT GREATEST('Sonu', 'Monu'), LEAST('Sonu', 'Monu') FROM DUAL;

SELECT * FROM EMP FETCH FIRST (SELECT COUNT(*) * 0.25 FROM EMP) ROWS ONLY;

SELECT E.*, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO FETCH NEXT 5 ROWS ONLY;
SELECT E.*, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO FETCH NEXT 1 ROWS ONLY;
SELECT E.*, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO OFFSET 2 ROWS FETCH NEXT 5 ROWS ONLY;

SELECT E.*, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO FETCH FIRST 5 ROWS ONLY;
SELECT E.*, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO FETCH FIRST 1 ROWS ONLY;
SELECT E.*, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO OFFSET 2 ROWS FETCH FIRST 5 ROWS ONLY;

SELECT E.*, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO FETCH NEXT 25 PERCENT ROWS ONLY;
SELECT E.*, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO OFFSET 2 ROWS FETCH NEXT 25 PERCENT ROWS ONLY;

SELECT E.*, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO FETCH FIRST 25 PERCENT ROWS ONLY;
SELECT E.*, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO OFFSET 2 ROWS FETCH FIRST 25 PERCENT ROWS ONLY;

SELECT E.*, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO FETCH FIRST 25 PERCENT ROWS WITH TIES;
SELECT E.*, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO OFFSET 2 ROWS FETCH FIRST 25 PERCENT ROWS WITH TIES;