-- Suppose you have two table table A and table B, table B
-- was exact replica of table A and A does not have primary key.
-- A new records comes into B from A which was already present in
-- B Then how to avoid inserting duplicates records in B?

-- CREATE TABLE CARS_A (
--     BRAND   VARCHAR2(50),
--     MODEL   VARCHAR2(50),
--     YEAR    NUMBER(4),
--     COLOR   VARCHAR2(30)
-- );

-- INSERT INTO CARS_A (BRAND, MODEL, YEAR, COLOR) VALUES ('Toyota', 'Camry', 2020, 'White');
-- INSERT INTO CARS_A (BRAND, MODEL, YEAR, COLOR) VALUES ('Honda', 'Civic', 2019, 'Black');
-- INSERT INTO CARS_A (BRAND, MODEL, YEAR, COLOR) VALUES ('Hyundai', 'Elantra', 2022, 'Silver');
-- INSERT INTO CARS_A (BRAND, MODEL, YEAR, COLOR) VALUES ('Ford', 'Mustang', 2023, 'Red');
-- COMMIT;

SELECT * FROM CARS_A;
SELECT * FROM CARS_B;

-- Method 1
INSERT INTO CARS_B (BRAND, MODEL, YEAR, COLOR)
SELECT
    A.BRAND,
    A.MODEL,
    A.YEAR,
    A.COLOR
FROM CARS_A A
WHERE NOT EXISTS(
    SELECT
        1
    FROM CARS_B B
    WHERE A.BRAND = B.BRAND
    AND A.MODEL = B.MODEL
    AND A.YEAR = B.YEAR
    AND A.COLOR = B.COLOR 
);

INSERT INTO cars_a VALUES ('Chevrolet', 'Malibu', 2018, 'Gray');
INSERT INTO cars_a VALUES ('BMW', 'X5', 2022, 'Black');
INSERT INTO cars_a VALUES ('Audi', 'A4', 2021, 'White');
INSERT INTO cars_a VALUES ('Kia', 'Seltos', 2020, 'Blue');
INSERT INTO cars_a VALUES ('Nissan', 'Altima', 2019, 'Red');
INSERT INTO cars_a VALUES ('Volkswagen', 'Passat', 2021, 'Silver');
INSERT INTO cars_a VALUES ('Mazda', 'CX-5', 2023, 'Gray');
INSERT INTO cars_a VALUES ('Tesla', 'Model 3', 2022, 'White');
INSERT INTO cars_a VALUES ('Toyota', 'Corolla', 2018, 'Blue');
INSERT INTO cars_a VALUES ('Hyundai', 'Tucson', 2021, 'Red');
INSERT INTO cars_a VALUES ('Honda', 'Accord', 2020, 'Black');
INSERT INTO cars_a VALUES ('Ford', 'Escape', 2019, 'White');
INSERT INTO cars_a VALUES ('Chevrolet', 'Equinox', 2023, 'Blue');
INSERT INTO cars_a VALUES ('BMW', '3 Series', 2020, 'Silver');
INSERT INTO cars_a VALUES ('Kia', 'Sportage', 2022, 'Black');

-- Method 2
MERGE INTO CARS_B B
USING CARS_A A
ON (
    A.BRAND = B.BRAND
    AND A.MODEL = B.MODEL
    AND A.YEAR = B.YEAR
    AND A.COLOR = B.COLOR
)
WHEN NOT MATCHED THEN
    INSERT (BRAND, MODEL, YEAR, COLOR)
    VALUES (A.BRAND, A.MODEL, A.YEAR, A.COLOR);


--
-- CREATE TABLE ACTIVITY (
--     MACHINE_ID     NUMBER(5),
--     PROCESS_ID     NUMBER(5),
--     ACTIVITY_TYPE  VARCHAR2(10),
--     TIMESTAMP      NUMBER(10,3)
-- );

-- INSERT INTO ACTIVITY (MACHINE_ID, PROCESS_ID, ACTIVITY_TYPE, TIMESTAMP) VALUES (0, 0, 'start', 0.712);
-- INSERT INTO ACTIVITY (MACHINE_ID, PROCESS_ID, ACTIVITY_TYPE, TIMESTAMP) VALUES (0, 0, 'end', 1.520);
-- INSERT INTO ACTIVITY (MACHINE_ID, PROCESS_ID, ACTIVITY_TYPE, TIMESTAMP) VALUES (0, 1, 'start', 3.140);
-- INSERT INTO ACTIVITY (MACHINE_ID, PROCESS_ID, ACTIVITY_TYPE, TIMESTAMP) VALUES (0, 1, 'end', 4.120);
-- INSERT INTO ACTIVITY (MACHINE_ID, PROCESS_ID, ACTIVITY_TYPE, TIMESTAMP) VALUES (1, 0, 'start', 0.550);
-- INSERT INTO ACTIVITY (MACHINE_ID, PROCESS_ID, ACTIVITY_TYPE, TIMESTAMP) VALUES (1, 0, 'end', 1.550);
-- INSERT INTO ACTIVITY (MACHINE_ID, PROCESS_ID, ACTIVITY_TYPE, TIMESTAMP) VALUES (1, 1, 'start', 0.430);
-- INSERT INTO ACTIVITY (MACHINE_ID, PROCESS_ID, ACTIVITY_TYPE, TIMESTAMP) VALUES (1, 1, 'end', 1.420);
-- INSERT INTO ACTIVITY (MACHINE_ID, PROCESS_ID, ACTIVITY_TYPE, TIMESTAMP) VALUES (2, 0, 'start', 4.100);
-- INSERT INTO ACTIVITY (MACHINE_ID, PROCESS_ID, ACTIVITY_TYPE, TIMESTAMP) VALUES (2, 0, 'end', 4.512);
-- INSERT INTO ACTIVITY (MACHINE_ID, PROCESS_ID, ACTIVITY_TYPE, TIMESTAMP) VALUES (2, 1, 'start', 2.500);
-- INSERT INTO ACTIVITY (MACHINE_ID, PROCESS_ID, ACTIVITY_TYPE, TIMESTAMP) VALUES (2, 1, 'end', 5.000);

-- COMMIT;

SELECT * FROM ACTIVITY;

-- Method 1
WITH RES AS(
    SELECT
        MACHINE_ID,
        PROCESS_ID,
        SUM(
            CASE
                WHEN ACTIVITY_TYPE = 'start' THEN -TIMESTAMP
                WHEN ACTIVITY_TYPE = 'end' THEN TIMESTAMP
            END
        ) AS TOTAL_TIME
    FROM
        ACTIVITY
    GROUP BY MACHINE_ID, PROCESS_ID
)
SELECT
    MACHINE_ID,
    AVG(TOTAL_TIME) AS PROCESSING_TIME
FROM
    RES
GROUP BY MACHINE_ID;

-- Method 2
SELECT
    A1.MACHINE_ID,
    ROUND(AVG(A2.TIMESTAMP - A1.TIMESTAMP), 3) AS PROCESSING_TIME
FROM
    ACTIVITY A1 INNER JOIN ACTIVITY A2
    ON A1.MACHINE_ID = A2.MACHINE_ID
    AND A1.PROCESS_ID = A2.PROCESS_ID
    AND A1.ACTIVITY_TYPE = 'start'
    AND A2.ACTIVITY_TYPE = 'end'
GROUP BY A1.MACHINE_ID;

-- 
-- Write a SQL query to find the each month total transactions with
-- total amount and total approved transactions with total amount.

-- CREATE TABLE TRANSACTIONS (
--     ID               NUMBER(5),
--     COUNTRY          VARCHAR2(20),
--     STATE            VARCHAR2(20),
--     AMOUNT           NUMBER(10,2),
--     TRANSACTION_DATE DATE
-- );

-- INSERT ALL
--     INTO TRANSACTIONS VALUES (1,'USA','APPROVED',120.50,TO_DATE('15-01-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (2,'INDIA','DECLINED',560.75,TO_DATE('10-02-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (3,'UK','APPROVED',980,TO_DATE('05-03-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (4,'CANADA','APPROVED',450.30,TO_DATE('20-04-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (5,'AUSTRALIA','DECLINED',1500,TO_DATE('25-05-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (6,'USA','DECLINED',210.90,TO_DATE('15-06-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (7,'INDIA','APPROVED',780.50,TO_DATE('05-07-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (8,'UK','DECLINED',320,TO_DATE('19-08-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (9,'CANADA','APPROVED',1550.25,TO_DATE('10-09-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (10,'AUSTRALIA','DECLINED',600,TO_DATE('01-10-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (11,'USA','APPROVED',890.75,TO_DATE('18-01-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (12,'INDIA','DECLINED',1020.40,TO_DATE('22-02-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (13,'UK','APPROVED',340.60,TO_DATE('15-03-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (14,'CANADA','DECLINED',4500,TO_DATE('28-04-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (15,'AUSTRALIA','APPROVED',275.80,TO_DATE('12-05-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (16,'USA','DECLINED',1999.99,TO_DATE('18-06-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (17,'INDIA','APPROVED',520,TO_DATE('09-07-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (18,'UK','DECLINED',880,TO_DATE('13-08-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (19,'CANADA','APPROVED',765.45,TO_DATE('25-09-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (20,'AUSTRALIA','DECLINED',640.25,TO_DATE('14-10-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (21,'USA','APPROVED',720,TO_DATE('25-01-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (22,'INDIA','DECLINED',120,TO_DATE('14-02-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (23,'UK','APPROVED',440.30,TO_DATE('30-03-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (24,'CANADA','DECLINED',150.50,TO_DATE('05-04-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (25,'AUSTRALIA','APPROVED',880,TO_DATE('18-05-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (26,'USA','DECLINED',1350,TO_DATE('25-06-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (27,'INDIA','APPROVED',2500,TO_DATE('28-07-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (28,'UK','DECLINED',3300.50,TO_DATE('30-08-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (29,'CANADA','APPROVED',420.75,TO_DATE('18-09-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (30,'AUSTRALIA','DECLINED',650,TO_DATE('08-10-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (31,'USA','APPROVED',980.80,TO_DATE('05-01-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (32,'INDIA','DECLINED',750,TO_DATE('27-02-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (33,'UK','APPROVED',2750.40,TO_DATE('12-03-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (34,'CANADA','DECLINED',1100,TO_DATE('25-04-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (35,'AUSTRALIA','APPROVED',530.90,TO_DATE('02-05-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (36,'USA','DECLINED',870,TO_DATE('09-06-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (37,'INDIA','APPROVED',1400,TO_DATE('21-07-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (38,'UK','DECLINED',2000,TO_DATE('04-08-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (39,'CANADA','APPROVED',333.33,TO_DATE('11-09-2024','DD-MM-YYYY'))
--     INTO TRANSACTIONS VALUES (40,'AUSTRALIA','DECLINED',650.50,TO_DATE('20-10-2024','DD-MM-YYYY'))
-- SELECT * FROM DUAL;

-- COMMIT;

SELECT * FROM transactions;

SELECT
    EXTRACT(MONTH FROM transaction_date) AS TXNS_MONTH,
    COUNTRY,
    COUNT(1) AS TOTAL_COUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT,
    SUM(CASE
        WHEN STATE = 'APPROVED' THEN 1
        ELSE 0
    END) AS TOTAL_APPROVED_COUNT,
    SUM(
        CASE
            WHEN STATE = 'APPROVED' THEN AMOUNT
            ELSE 0
        END
    ) AS TOTAL_APPROVED_AMOUNT,
    SUM(CASE
        WHEN STATE = 'DECLINED' THEN 1
        ELSE 0
    END) AS TOTAL_DECLINED_COUNT,
    SUM(
        CASE
            WHEN STATE = 'DECLINED' THEN AMOUNT
            ELSE 0
        END
    ) AS TOTAL_DECLINED_AMOUNT
FROM transactions
GROUP BY EXTRACT(MONTH FROM transaction_date), COUNTRY;

SELECT
    DISTINCT
    EXTRACT(MONTH FROM transaction_date) AS TXNS_MONTH,
    COUNTRY,
    COUNT(1) OVER(PARTITION BY EXTRACT(MONTH FROM transaction_date), COUNTRY) AS TOTAL_TXNS_COUNT,
    SUM(AMOUNT) OVER(PARTITION BY EXTRACT(MONTH FROM transaction_date), COUNTRY) AS TOTAL_TXNS_AMOUNT,
    COUNT(CASE WHEN STATE = 'APPROVED' THEN 1 ELSE 0 END) OVER(PARTITION BY EXTRACT(MONTH FROM transaction_date), COUNTRY) AS TOTAL_APPROVED_COUNT,
    SUM(CASE WHEN STATE = 'APPROVED' THEN AMOUNT ELSE 0 END) OVER(PARTITION BY EXTRACT(MONTH FROM transaction_date), COUNTRY) AS TOTAL_APPROVED_AMOUNT
FROM transactions;

-- 
-- CREATE TABLE EMPLOYEE_SWIPE (
--     EMP_ID         NUMBER(5),
--     SWIPE_TIME     VARCHAR2(10),
--     STATUS         VARCHAR2(5),
--     MANAGER_NAME   VARCHAR2(100),
--     PROJECT_NAME   VARCHAR2(100)
-- );

-- INSERT ALL
-- INTO EMPLOYEE_SWIPE VALUES (101, '13-08-2025  09:01:00', 'IN',  'Alice Johnson',  'Project Alpha')
-- INTO EMPLOYEE_SWIPE VALUES (101, '13-08-2025  18:15:00', 'OUT', 'Alice Johnson',  'Project Alpha')
-- INTO EMPLOYEE_SWIPE VALUES (102, '13-08-2025  08:55:00', 'IN',  'Bob Smith',      'Project Beta')
-- INTO EMPLOYEE_SWIPE VALUES (102, '13-08-2025  12:30:00', 'OUT', 'Bob Smith',      'Project Beta')
-- INTO EMPLOYEE_SWIPE VALUES (102, '13-08-2025  13:20:00', 'IN',  'Bob Smith',      'Project Beta')
-- INTO EMPLOYEE_SWIPE VALUES (102, '13-08-2025  17:40:00', 'OUT', 'Bob Smith',      'Project Beta')
-- INTO EMPLOYEE_SWIPE VALUES (103, '13-08-2025  09:10:00', 'IN',  'Charlie Evans',  'Project Gamma')
-- INTO EMPLOYEE_SWIPE VALUES (104, '13-08-2025  09:05:00', 'IN',  'Diana White',    'Project Delta')
-- INTO EMPLOYEE_SWIPE VALUES (104, '13-08-2025  18:10:00', 'OUT', 'Diana White',    'Project Delta')
-- INTO EMPLOYEE_SWIPE VALUES (105, '13-08-2025  09:00:00', 'IN',  'Ethan Brown',    'Project Alpha')
-- INTO EMPLOYEE_SWIPE VALUES (105, '13-08-2025  12:45:00', 'OUT', 'Ethan Brown',    'Project Alpha')
-- INTO EMPLOYEE_SWIPE VALUES (105, '13-08-2025  13:35:00', 'IN',  'Ethan Brown',    'Project Alpha')
-- INTO EMPLOYEE_SWIPE VALUES (106, '13-08-2025  08:50:00', 'IN',  'Fiona Harris',   'Project Beta')
-- INTO EMPLOYEE_SWIPE VALUES (106, '13-08-2025  17:50:00', 'OUT', 'Fiona Harris',   'Project Beta')
-- INTO EMPLOYEE_SWIPE VALUES (107, '13-08-2025  09:15:00', 'IN',  'George Clark',   'Project Gamma')
-- INTO EMPLOYEE_SWIPE VALUES (108, '13-08-2025  09:03:00', 'IN',  'Hannah Scott',   'Project Delta')
-- INTO EMPLOYEE_SWIPE VALUES (108, '13-08-2025  18:18:00', 'OUT', 'Hannah Scott',   'Project Delta')
-- INTO EMPLOYEE_SWIPE VALUES (109, '13-08-2025  09:07:00', 'IN',  'Ian Miller',     'Project Alpha')
-- INTO EMPLOYEE_SWIPE VALUES (110, '13-08-2025  08:58:00', 'IN',  'Jack Wilson',    'Project Beta')
-- INTO EMPLOYEE_SWIPE VALUES (110, '13-08-2025  17:58:00', 'OUT', 'Jack Wilson',    'Project Beta')
-- SELECT * FROM DUAL;

-- COMMIT;

SELECT * FROM emp_swipe_log;

SELECT
    EMP_ID,
    SWIPE_TIME,
    status
FROM EMP_SWIPE_LOG
GROUP BY EMP_ID, SWIPE_TIME, status
ORDER BY EMP_ID, SWIPE_TIME DESC;

WITH FINAL AS(
    SELECT
        EMP_ID,
        SWIPE_TIME,
        STATUS,
        ROW_NUMBER() OVER(PARTITION BY EMP_ID ORDER BY EMP_ID, SWIPE_TIME DESC) AS RN
    FROM
        EMP_SWIPE_LOG
)
SELECT
    EMP_ID,
    SWIPE_TIME
FROM FINAL
WHERE
    RN = 1
    AND STATUS = 'IN';

--
-- CREATE TABLE consecutive_vals (
--     ID   NUMBER(5),
--     VAL  NUMBER(5)
-- );

-- INSERT ALL
--     INTO consecutive_vals VALUES (1, 1)
--     INTO consecutive_vals VALUES (2, 1)
--     INTO consecutive_vals VALUES (3, 1)
--     INTO consecutive_vals VALUES (4, 2)
--     INTO consecutive_vals VALUES (5, 2)
--     INTO consecutive_vals VALUES (6, 2)
--     INTO consecutive_vals VALUES (7, 2)
--     INTO consecutive_vals VALUES (8, 2)
--     INTO consecutive_vals VALUES (9, 3)
--     INTO consecutive_vals VALUES (10, 3)
--     INTO consecutive_vals VALUES (11, 4)
--     INTO consecutive_vals VALUES (12, 4)
--     INTO consecutive_vals VALUES (13, 4)
--     INTO consecutive_vals VALUES (14, 4)
--     INTO consecutive_vals VALUES (15, 4)
--     INTO consecutive_vals VALUES (16, 5)
--     INTO consecutive_vals VALUES (17, 1)
--     INTO consecutive_vals VALUES (18, 1)
--     INTO consecutive_vals VALUES (19, 1)
-- SELECT * FROM DUAL;

-- COMMIT;

SELECT * FROM consecutive_vals;

WITH RES AS(
    SELECT
        val,
        LEAD(val, 1) OVER(ORDER BY id) as ONE,
        LEAD(val, 2) OVER(ORDER BY id) as TWO
    FROM consecutive_vals
)
SELECT DISTINCT VAL FROM RES WHERE VAL = ONE AND VAL = TWO;

SELECT
    DISTINCT
    curr.val
FROM
    consecutive_vals curr
    INNER JOIN consecutive_vals next ON curr.id = next.id - 1
    INNER JOIN consecutive_vals prev ON curr.id = prev.id + 1
WHERE
    curr.val = next.val
    and curr.val = prev.val;

-- 
-- CREATE TABLE test_values (
--     ID   NUMBER(5),
--     VAL  NUMBER(5)
-- );

-- INSERT ALL
-- INTO test_values VALUES (1, 10)
-- INTO test_values VALUES (2, NULL)
-- INTO test_values VALUES (3, NULL)
-- INTO test_values VALUES (4, 40)
-- INTO test_values VALUES (5, NULL)
-- INTO test_values VALUES (6, 30)
-- INTO test_values VALUES (7, 25)
-- INTO test_values VALUES (8, NULL)
-- INTO test_values VALUES (9, 30)
-- SELECT * FROM DUAL;

-- COMMIT;

SELECT * FROM test_values;

-- Method 1
SELECT
    id,
    val,
    LAST_VALUE(val IGNORE NULLS) OVER (ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS filled_val
FROM test_values;

-- Method 2
SELECT
    id,
    val,
    COALESCE(val, LAG(val IGNORE NULLS) OVER (ORDER BY id)) AS filled_val
FROM TEST_VALUES;

-- Method 3
WITH fill_cte (id, val, filled_val) AS (
    SELECT
        id,
        val,
        val
    FROM
        test_values
    WHERE id = 1
    UNION ALL
    SELECT
        t.id,
        t.val,
        COALESCE(t.val, f.filled_val)
    FROM
        test_values t
        JOIN fill_cte f ON t.id = f.id + 1
) SELECT * FROM fill_cte;