-- UPDATE DEPARTMENT NAMES BASED ON DEPTNO

-- CREATE TABLE EMP_INT (
--     EMPID       NUMBER(5),
--     ENAME       VARCHAR2(50),
--     DEPTNO      NUMBER(2),
--     SALARY      NUMBER(10,2),
--     JOB         VARCHAR2(30),
--     DEPT_NAME   VARCHAR2(50)
-- );

-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (103, 'Charlie', 30, 40000, 'CLERK', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (109, 'Ian', 30, 61000, 'ANALYST', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (106, 'Frank', 30, 46000, 'CLERK', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (106, 'Frank', 30, 46000, 'CLERK', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (106, 'Frank', 30, 46000, 'CLERK', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (102, 'Bob', 20, 62000, 'ANALYST', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (108, 'Helen', 20, 56000, 'SALESMAN', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (105, 'Eve', 10, 52000, 'SALESMAN', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (101, 'Alice', 10, 85000, 'MANAGER', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (107, 'Grace', 10, 73000, 'MANAGER', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (110, 'Jane', 30, 80000, 'MANAGER', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (110, 'Jane', 30, 80000, 'MANAGER', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (110, 'Jane', 30, 80000, 'MANAGER', NULL);
-- INSERT INTO EMP_INT (EMPID, ENAME, DEPTNO, SALARY, JOB, DEPT_NAME) VALUES (104, 'David', 10, 95000, 'PRESIDENT', NULL);
-- COMMIT;

SELECT * FROM EMP_INT;

UPDATE EMP_INT 
SET
DEPT_NAME = (
    CASE
        WHEN DEPTNO = 10
            THEN 'ENGINEERING'
        WHEN DEPTNO = 20
            THEN 'SALES'
        ELSE 'HR'
    END
);

SELECT * FROM EMP_INT;

UPDATE EMP_INT SET DEPT_NAME = (
    CASE
        WHEN DEPT_NAME = 'HR'
        THEN 'CLOUD'
        ELSE DEPT_NAME
    END
);

-- SELECT ALL EMPLOYEE WHO EARNS MORE THAN THEIR MANAGER
SELECT * FROM EMP;

SELECT
    E.EMPNO,
    E.ENAME,
    E.SAL AS SALARY,
    M.EMPNO AS MGR_ID,
    M.ENAME AS MGR_NAME,
    M.SAL AS MGR_SALARY
FROM
    EMP E INNER JOIN EMP M
    ON E.MGR = M.EMPNO AND E.SAL > M.SAL;


-- Query to get running total of profit and change in profit compared to previous day

-- CREATE TABLE TXNS (
--     TXNS_ID    NUMBER(5),
--     TXNS_DATE  DATE,
--     PROFIT     NUMBER(10,2)
-- );

-- INSERT INTO TXNS (TXNS_ID, TXNS_DATE, PROFIT) VALUES (1, TO_DATE('23-02-2025', 'DD-MM-YYYY'), 10);
-- INSERT INTO TXNS (TXNS_ID, TXNS_DATE, PROFIT) VALUES (2, TO_DATE('24-02-2025', 'DD-MM-YYYY'), 20);
-- INSERT INTO TXNS (TXNS_ID, TXNS_DATE, PROFIT) VALUES (3, TO_DATE('25-02-2025', 'DD-MM-YYYY'), 5);
-- INSERT INTO TXNS (TXNS_ID, TXNS_DATE, PROFIT) VALUES (4, TO_DATE('26-02-2025', 'DD-MM-YYYY'), 100);
-- INSERT INTO TXNS (TXNS_ID, TXNS_DATE, PROFIT) VALUES (5, TO_DATE('27-02-2025', 'DD-MM-YYYY'), 34);
-- COMMIT;

SELECT * FROM TXNS;

WITH RES AS(
    SELECT
        T.*,
        SUM(T.PROFIT) OVER(ORDER BY T.TXNS_DATE DESC) AS RUNNING_PROFIT,
        LAG(T.PROFIT) OVER(ORDER BY T.TXNS_DATE DESC) AS PREV_VAL
    FROM TXNS T
)
SELECT
    TXNS_ID,
    TXNS_DATE,
    PROFIT,
    RUNNING_PROFIT,
    CASE
        WHEN PREV_VAL > PROFIT THEN 'Decrease'
        WHEN PREV_VAL < PROFIT THEN 'Increase'
        ELSE 'No Change'
    END AS CHNAGE_IN_VALUE
FROM
    RES;

-- 

-- CREATE TABLE QUES1 (
--     NAME    VARCHAR2(50),
--     SKILLS  VARCHAR2(200)
-- );

-- INSERT INTO QUES1 (NAME, SKILLS) VALUES ('Shiv', '[C++, C, Python, Java]');
-- INSERT INTO QUES1 (NAME, SKILLS) VALUES ('Ram', '[C++, C, Java]');
-- INSERT INTO QUES1 (NAME, SKILLS) VALUES ('Ritika', '[C++, C]');
-- INSERT INTO QUES1 (NAME, SKILLS) VALUES ('Rashi', '[C++, C, Python]');
-- COMMIT;

SELECT * FROM QUES1;

WITH RES AS(
    SELECT
        NAME,
        (LENGTH(SKILLS) - LENGTH(REPLACE(SKILLS, ',', '')) + 1) AS SKILL_COUNT
    FROM
        QUES1
)
SELECT
    NAME,
    SKILL_COUNT
FROM RES ORDER BY SKILL_COUNT DESC FETCH FIRST 1 ROW ONLY;