-- Find the second highest salary without TOP, LIMIT, or RANK
SELECT * FROM EMP;

SELECT
    MAX(SAL) AS SECOND_MAX
FROM
    EMP
WHERE
    SAL < (SELECT MAX(SAL) FROM EMP);

-- Detect and delete duplicate rows
-- CREATE TABLE duplicates(
--     ID int,
--     name VARCHAR2(50)
-- )

-- INSERT INTO DUPLICATES VALUES(1, 'Sonu');
-- INSERT INTO DUPLICATES VALUES(2, 'Monu');
-- INSERT INTO DUPLICATES VALUES(3, 'Rashi');
-- INSERT INTO DUPLICATES VALUES(3, 'Abhi');
-- INSERT INTO DUPLICATES VALUES(5, 'Sid');
-- INSERT INTO DUPLICATES VALUES(1, 'Aman');
-- INSERT INTO DUPLICATES VALUES(2, 'Sonu');
-- INSERT INTO DUPLICATES VALUES(2, 'Anshu');
-- INSERT INTO DUPLICATES VALUES(3, 'Sonu');
-- INSERT INTO DUPLICATES VALUES(4, 'Arav');
-- INSERT INTO DUPLICATES VALUES(3, 'Sonu');
-- INSERT INTO DUPLICATES VALUES(7, 'Manav');
-- INSERT INTO DUPLICATES VALUES(8, 'Ritika');
-- COMMIT;

SELECT ROWID, D.* FROM DUPLICATES D;

SELECT ID, COUNT(*) AS CNT FROM DUPLICATES GROUP BY ID HAVING COUNT(*) > 1;
SELECT ID, MIN(ROWID) AS CNT FROM DUPLICATES GROUP BY ID;

DELETE FROM DUPLICATES D1
WHERE ROWID > (
    SELECT
        MIN(ROWID)
    FROM
        DUPLICATES D2
    WHERE D1.ID = D2.ID 
);

-- Query to find Winning Streak
-- CREATE TABLE STREAK(
--     ID INT,
--     status VARCHAR2(10)
-- )

-- INSERT INTO STREAK VALUES(1, 'W');
-- INSERT INTO STREAK VALUES(2, 'L');
-- INSERT INTO STREAK VALUES(3, 'W');
-- INSERT INTO STREAK VALUES(4, 'W');
-- INSERT INTO STREAK VALUES(5, 'W');
-- INSERT INTO STREAK VALUES(6, 'L');
-- INSERT INTO STREAK VALUES(7, 'L');
-- INSERT INTO STREAK VALUES(8, 'W');
-- INSERT INTO STREAK VALUES(9, 'L');
-- INSERT INTO STREAK VALUES(10, 'W');
-- INSERT INTO STREAK VALUES(11, 'W');
-- INSERT INTO STREAK VALUES(12, 'W');
-- INSERT INTO STREAK VALUES(13, 'W');
-- INSERT INTO STREAK VALUES(14, 'L');
-- INSERT INTO STREAK VALUES(15, 'W');
-- INSERT INTO STREAK VALUES(16, 'W');

-- COMMIT;

SELECT * FROM STREAK;

WITH RES AS(
    SELECT
        ID,
        STATUS,
        ROW_NUMBER() OVER(ORDER BY ID) RN1,
        ROW_NUMBER() OVER(PARTITION BY STATUS ORDER BY ID) AS RN2,
        ROW_NUMBER() OVER(ORDER BY ID) - ROW_NUMBER() OVER(PARTITION BY STATUS ORDER BY ID) AS RN3
    FROM
        STREAK
)
SELECT
    MIN(ID) AS START_ID,
    MAX(ID) AS END_ID,
    COUNT(*) AS STREAK_LENGTH
FROM
    RES
WHERE STATUS = 'W'
GROUP BY RN3;