-- VANGUARD QUESTION 1

SELECT * FROM SALARY ORDER BY TENURE;

WITH SAL AS (
    SELECT
        TENURE,
        SALARY,
        NTH_VALUE(SALARY, 2) OVER(PARTITION BY TENURE ORDER BY SALARY DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS VAL_0,
        NTH_VALUE(SALARY, 2) OVER(PARTITION BY TENURE ORDER BY SALARY DESC) AS VAL
    FROM SALARY
) SELECT * FROM SAL WHERE VAL IS NOT NULL;

-- Query to get the 2nd lowest salary for each tenure
WITH SAL AS (
    SELECT
        TENURE,
        SALARY,
        DENSE_RANK() OVER(PARTITION BY TENURE ORDER BY SALARY ASC) AS DN
    FROM
        SALARY
)
SELECT TENURE, SALARY, DN FROM SAL WHERE DN = 2;

-- Query to get the 2nd highest salary for each tenure, if not available get the highest salary
WITH SAL AS (
    SELECT
        TENURE,
        SALARY,
        DENSE_RANK() OVER(PARTITION BY TENURE ORDER BY SALARY DESC) AS DN
    FROM SALARY
), SECOND AS(
    SELECT * FROM SAL WHERE DN = 2
), FIRST AS (
    SELECT
        *
    FROM
        SAL
    WHERE
        TENURE NOT IN (SELECT DISTINCT TENURE FROM SECOND) AND
        DN = 1
), RES AS(
    SELECT TENURE, SALARY FROM FIRST
    UNION
    SELECT TENURE, SALARY FROM SECOND
) SELECT * FROM RES ORDER BY TENURE;


-- VANGUARD QUESTION 2

SELECT * FROM FUND_ALLOCATION;
SELECT * FROM FUND;

-- Method 1: Query to fund allocation using multiple joins
SELECT
    F.PARTID,
    F.FUNDID,
    F.BALANCE,
    F.BALANCE * A1.ALLOCATION_PERCENTAGE AS BOND,
    F.BALANCE * A2.ALLOCATION_PERCENTAGE AS CASH,
    F.BALANCE * A3.ALLOCATION_PERCENTAGE AS CTSK
FROM
    FUND F
    LEFT JOIN FUND_ALLOCATION A1 ON F.FUNDID = A1.FUNDID AND A1.ALLOCATION_TYPE = 'BOND'
    LEFT JOIN FUND_ALLOCATION A2 ON F.FUNDID = A2.FUNDID AND A2.ALLOCATION_TYPE = 'CASH'
    LEFT JOIN FUND_ALLOCATION A3 ON F.FUNDID = A3.FUNDID AND A3.ALLOCATION_TYPE = 'CTSK';

-- Method 2: Query to fund allocation using conditional aggregation
SELECT
    F.PARTID,
    F.FUNDID,
    F.BALANCE,
    ROUND(SUM(CASE WHEN A.ALLOCATION_TYPE = 'BOND' THEN A.ALLOCATION_PERCENTAGE * F.BALANCE ELSE 0 END), 2) AS BOND,
    ROUND(SUM(CASE WHEN A.ALLOCATION_TYPE = 'CASH' THEN A.ALLOCATION_PERCENTAGE * F.BALANCE ELSE 0 END), 2) AS CASH,
    ROUND(SUM(CASE WHEN A.ALLOCATION_TYPE = 'CTSK' THEN A.ALLOCATION_PERCENTAGE * F.BALANCE ELSE 0 END), 2) AS CTSK
FROM
    FUND F
    LEFT JOIN FUND_ALLOCATION A ON F.FUNDID = A.FUNDID
GROUP BY F.PARTID, F.FUNDID, F.BALANCE;

-- VANGUARD QUESTION 3

SELECT * FROM STOCK_PRICES;

-- Method 1: Query to get count of days stock price increased by more than 5%
WITH RES AS(
    SELECT
        STOCK,
        (CLOSE_PRICE - OPEN_PRICE) / OPEN_PRICE AS PER
    FROM STOCK_PRICES
)
SELECT
    STOCK,
    COUNT(*) CNT
FROM
    RES
WHERE PER > 0.05
GROUP BY STOCK;

-- Method 2: Query to get count of days stock price increased by more than 5%
SELECT
    STOCK,
    COUNT(*) AS CNT
FROM
    STOCK_PRICES
WHERE
    ((CLOSE_PRICE - OPEN_PRICE) / OPEN_PRICE) > 0.05
GROUP BY STOCK;

-- VANGUARD QUESTION 4
SELECT * FROM SALES;

-- Method 1: Query to get total sales by department and percentage contribution
SELECT
    DISTINCT DEPARTMENT_ID,
    SUM(TOTAL_SALES) OVER(PARTITION BY DEPARTMENT_ID) AS DEPARTMENT_TOTAL_SALES,
    ROUND((SUM(TOTAL_SALES) OVER(PARTITION BY DEPARTMENT_ID) / SUM(TOTAL_SALES) OVER()) * 100, 2) AS SALES_PERCENTAGE_BY_DEPARTMENT
FROM SALES;

-- Method 2: Query to get total sales by department and percentage contribution
SELECT
    SALES_ID, EMPLOYEE_NAME, DEPARTMENT_ID, TOTAL_SALES,
    ROUND((TOTAL_SALES / SUM(TOTAL_SALES) OVER()) * 100, 2) AS PERCENTAGE
FROM SALES;

-- VANGUARD QUESTION 5
SELECT * FROM SALES;

SELECT
    SALES_ID,
    TOTAL_SALES,
    LAG(TOTAL_SALES) OVER(ORDER BY SALES_ID) PREV_SALES,
    LEAD(TOTAL_SALES) OVER(ORDER BY SALES_ID) NEXT_SALES,
    LAG(TOTAL_SALES, 2) OVER(ORDER BY SALES_ID) PREV_2_SALES,
    LEAD(TOTAL_SALES, 2) OVER(ORDER BY SALES_ID) NEXT_2_SALES
FROM SALES;