-- UPDATE DEPARTMENT NAMES BASED ON DEPTNO

SELECT * FROM EMP_INT;

UPDATE EMP_INT 
SET
DEPT_NAME = (
    CASE
        WHEN DEPTNO = 10
            THEN 'ENGINEERING'
        WHEN DEPTNO = 20
            THEN 'SALES'
        ELSE 'HR'
    END
);

SELECT * FROM EMP_INT;

UPDATE EMP_INT SET DEPT_NAME = (
    CASE
        WHEN DEPT_NAME = 'HR'
        THEN 'CLOUD'
        ELSE DEPT_NAME
    END
);

-- SELECT ALL EMPLOYEE WHO EARNS MORE THAN THEIR MANAGER
SELECT * FROM EMP;

SELECT
    E.EMPNO,
    E.ENAME,
    E.SAL AS SALARY,
    M.EMPNO AS MGR_ID,
    M.ENAME AS MGR_NAME,
    M.SAL AS MGR_SALARY
FROM
    EMP E INNER JOIN EMP M
    ON E.MGR = M.EMPNO AND E.SAL > M.SAL;


-- Query to get running total of profit and change in profit compared to previous day

SELECT * FROM TXNS;

WITH RES AS(
    SELECT
        T.*,
        SUM(T.PROFIT) OVER(ORDER BY T.TXNS_DATE DESC) AS RUNNING_PROFIT,
        LAG(T.PROFIT) OVER(ORDER BY T.TXNS_DATE DESC) AS PREV_VAL
    FROM TXNS T
)
SELECT
    TXNS_ID,
    TXNS_DATE,
    PROFIT,
    RUNNING_PROFIT,
    CASE
        WHEN PREV_VAL > PROFIT THEN 'Decrease'
        WHEN PREV_VAL < PROFIT THEN 'Increase'
        ELSE 'No Change'
    END AS CHNAGE_IN_VALUE
FROM
    RES;

-- 

SELECT * FROM QUES1;

WITH RES AS(
    SELECT
        NAME,
        (LENGTH(SKILLS) - LENGTH(REPLACE(SKILLS, ',', '')) + 1) AS SKILL_COUNT
    FROM
        QUES1
)
SELECT
    NAME,
    SKILL_COUNT
FROM RES ORDER BY SKILL_COUNT DESC FETCH FIRST 1 ROW ONLY;