-- Null is not a value its state
-- joins not get performed based on NULL values of a column

-- CREATE TABLE A1(ID INT, NAME VARCHAR2(10));
-- CREATE TABLE A2(ID INT, NAME VARCHAR2(10));
-- CREATE TABLE A3(VAL INT);
-- CREATE TABLE A4(VAL INT);
-- TRUNCATE TABLE A1;
-- TRUNCATE TABLE A2;

-- INSERT INTO A1 VALUES(1, 'A');
-- INSERT INTO A1 VALUES(1, 'B');
-- INSERT INTO A1 VALUES(2, 'C');
-- INSERT INTO A1 VALUES(3, 'E');
-- INSERT INTO A1 VALUES(3, 'R');
-- INSERT INTO A1 VALUES(4, 'A');
-- INSERT INTO A1 VALUES(5, 'C');
-- INSERT INTO A1 VALUES(NULL, 'QW');

-- INSERT INTO A2 VALUES(1, 'N');
-- INSERT INTO A2 VALUES(2, 'R');
-- INSERT INTO A2 VALUES(3, 'R');
-- INSERT INTO A2 VALUES(4, 'E');
-- INSERT INTO A2 VALUES(7, 'Q');
-- INSERT INTO A2 VALUES(8, 'Z');
-- INSERT INTO A2 VALUES(NULL, 'W');
-- INSERT INTO A2 VALUES(NULL, 'QQ');
-- INSERT INTO A2 VALUES(NULL, NULL);

-- INSERT INTO A3 VALUES(1);
-- INSERT INTO A3 VALUES(1);
-- INSERT INTO A3 VALUES(2);
-- INSERT INTO A3 VALUES(2);
-- INSERT INTO A3 VALUES(NULL);

-- INSERT INTO A4 VALUES(1);
-- INSERT INTO A4 VALUES(1);
-- INSERT INTO A4 VALUES(1);
-- INSERT INTO A4 VALUES(NULL);
-- INSERT INTO A4 VALUES(2);
-- COMMIT;

SELECT * FROM A1;
SELECT * FROM A2;

SELECT COUNT(*) FROM A2;
SELECT COUNT(1) FROM A2;

SELECT * FROM A1 WHERE ID IS NULL;

SELECT A1.*, 'INNER' FROM A1 INNER JOIN A2 ON A1.ID = A2.ID;

SELECT COUNT(*), 'INNER' FROM A1 INNER JOIN A2 ON A1.ID = A2.ID;
SELECT A1.ID, A1.NAME AS A1_NAME, A2.NAME AS A2_NAME, 'INNER' AS JOIN_TYPE FROM A1 INNER JOIN A2 ON A1.ID = A2.ID;

SELECT COUNT(*), 'LEFT' FROM A1 LEFT JOIN A2 ON A1.ID = A2.ID;
SELECT A1.ID, A1.NAME AS A1_NAME, A2.NAME AS A2_NAME, 'LEFT' AS JOIN_TYPE FROM A1 LEFT JOIN A2 ON A1.ID = A2.ID;

SELECT COUNT(*), 'RIGHT' FROM A1 RIGHT JOIN A2 ON A1.ID = A2.ID;
SELECT A2.ID, A1.NAME AS A1_NAME, A2.NAME AS A2_NAME, 'RIGHT' AS JOIN_TYPE FROM A1 RIGHT JOIN A2 ON A1.ID = A2.ID;

SELECT COUNT(*), 'FULL' FROM A1 FULL JOIN A2 ON A1.ID = A2.ID;
SELECT A1.ID, A1.NAME AS A1_NAME, A2.NAME AS A2_NAME, 'FULL' AS JOIN_TYPE FROM A1 FULL JOIN A2 ON A1.ID = A2.ID;

SELECT A2.ID, A2.NAME AS A2_NAME, 'LEFT ANTI' AS JOIN_TYPE
FROM A1 FULL JOIN A2 ON A1.ID = A2.ID WHERE A1.ID IS NUll AND A1.NAME IS NULL;

SELECT * FROM A1;

SELECT COUNT(*) FROM A1;
SELECT COUNT(1) FROM A1;

SELECT COUNT(ID) FROM A1;
SELECT COUNT(DISTINCT ID) FROM A1;
SELECT COUNT(ALL ID) FROM A1;

SELECT COUNT(NAME) FROM A1;
SELECT COUNT(DISTINCT NAME) FROM A1;
SELECT COUNT(ALL NAME) FROM A1;

SELECT * FROM A2;
SELECT COUNT(*) FROM A2;
SELECT COUNT(ID) FROM A2;

-- NULL is not a values its a state
SELECT * FROM A2 WHERE ID IS NULL;
SELECT * FROM A2 WHERE ID = NULL;

-- NULL does not take part in comparision

SELECT * FROM A3;
SELECT * FROM A4;

SELECT * FROM A3 INNER JOIN A4 ON A4.VAL = A3.VAL;
SELECT * FROM A3 LEFT JOIN A4 ON A4.VAL = A3.VAL;

-- 
-- CREATE TABLE CUST(
--     cust_id NUMBER,
--     name VARCHAR2(100)
-- );

-- CREATE TABLE ORD(
--     ID NUMBER,
--     CUST_ID NUMBER,
--     PROD_ID NUMBER
-- );

-- CREATE TABLE PROD(
--     ID NUMBER,
--     NAME VARCHAR2(100)
-- );

-- INSERT INTO CUST VALUES(1, 'John');
-- INSERT INTO CUST VALUES(2, 'Max');
-- INSERT INTO CUST VALUES(3, 'Bill');
-- INSERT INTO CUST VALUES(4, 'Sam');

-- INSERT INTO ORD VALUES(1, 3, 1);
-- INSERT INTO ORD VALUES(2, 1, 2);
-- INSERT INTO ORD VALUES(3, 1, 1);
-- INSERT INTO ORD VALUES(4, 2, 3);

-- INSERT INTO PROD VALUES(1, 'IPhone');
-- INSERT INTO PROD VALUES(2, 'Samsung');
-- INSERT INTO PROD VALUES(3, 'Xiomi');
-- COMMIT;

SELECT * FROM CUST;
SELECT * FROM PROD;
SELECT * FROM ORD;

-- Total Purchases by each customers
WITH RES AS(
    SELECT
        CUST_ID,
        COUNT(*) AS CNT
    FROM
        ORD
    GROUP BY CUST_ID
)
SELECT
    CUST.CUST_ID,
    CUST.NAME,
    RES.CNT AS TOTAL_PURCHASES
FROM
    CUST
    INNER JOIN RES
    ON RES.CUST_ID = CUST.CUST_ID;

-- Query to get customers who bought anything
SELECT * FROM CUST WHERE CUST_ID IN (SELECT DISTINCT CUST_ID FROM ORD);
SELECT * FROM CUST WHERE EXISTS (SELECT 1 FROM ORD WHERE ORD.CUST_ID = CUST.CUST_ID) ORDER BY CUST.CUST_ID;

-- Query to get the customer who hasn't bought anything
SELECT * FROM CUST WHERE CUST_ID NOT IN (SELECT DISTINCT CUST_ID FROM ORD);
SELECT * FROM CUST WHERE NOT EXISTS (SELECT 1 FROM ORD WHERE ORD.CUST_ID = CUST.CUST_ID) ORDER BY CUST.CUST_ID;

-- SELECT
--     *
-- FROM CUST INNER JOIN ORD ON CUST.CUST_ID = ORD.CUST_ID

-- Query to get customers who has IPHONE & SAMSUNG, but not XIOMI
WITH RES AS(
    SELECT
        CUST_ID,
        SUM(CASE WHEN ORD.PROD_ID = 1 THEN 1 ELSE 0 END) AS IPHONE,
        SUM(CASE WHEN ORD.PROD_ID = 2 THEN 1 ELSE 0 END) AS SAMSUNG,
        SUM(CASE WHEN ORD.PROD_ID = 3 THEN 1 ELSE 0 END) AS XIOMI
    FROM
        ORD
    GROUP BY CUST_ID
)
SELECT
    *
FROM
    RES
WHERE
    IPHONE <> 0 AND SAMSUNG <> 0 AND XIOMI = 0;


-- create table tmp1(id int);
-- INSERT INTO TMP1 VALUES(1);
-- INSERT INTO TMP1 VALUES(2);
-- INSERT INTO TMP1 VALUES(4);
-- INSERT INTO TMP1 VALUES(5);
-- INSERT INTO TMP1 VALUES(9);
-- INSERT INTO TMP1 VALUES(10);
-- COMMIT;

-- Query to get missing values using recursive CTEs
SELECT * FROM TMP1;

WITH REC(N) AS(
    SELECT 1 FROM DUAL
    UNION ALL
    SELECT N + 1 FROM REC WHERE N < (SELECT MAX(ID) FROM TMP1)
),
RES AS(
    SELECT
        A.N AS ID_1,
        B.ID AS ID_2
    FROM
        REC A LEFT JOIN TMP1 B ON A.N = B.ID 
)
SELECT
    ID_1 AS ID
FROM RES
WHERE ID_2 IS NULL
ORDER BY ID_1;

-- Query to find out flags reviewed by youtube for the videos
-- that most no of user flags
-- CREATE TABLE USER_FLAG (
--     FLAG_ID NUMBER,
--     VIDEO_ID VARCHAR2(20),
--     USER_FIRSTNAME VARCHAR2(50)
-- );

-- CREATE TABLE FLAG_REVIEW (
--     FLAG_ID NUMBER,
--     REVIEWED_BY_YOUTUBE VARCHAR2(10)
-- );

-- INSERT INTO USER_FLAG VALUES (1, 'V1001', 'Alice');
-- INSERT INTO USER_FLAG VALUES (2, 'V1001', 'Bob');
-- INSERT INTO USER_FLAG VALUES (3, 'V1001', 'Charlie');
-- INSERT INTO USER_FLAG VALUES (4, 'V1002', 'David');
-- INSERT INTO USER_FLAG VALUES (5, 'V1002', 'Eva');
-- INSERT INTO USER_FLAG VALUES (6, 'V1003', 'Frank');
-- INSERT INTO USER_FLAG VALUES (7, 'V1003', 'Grace');
-- INSERT INTO USER_FLAG VALUES (8, 'V1003', 'Helen');
-- INSERT INTO USER_FLAG VALUES (9, 'V1003', 'Ivy');
-- INSERT INTO USER_FLAG VALUES (10, 'V1004', 'Jack');

-- INSERT INTO FLAG_REVIEW VALUES (1, 'TRUE');
-- INSERT INTO FLAG_REVIEW VALUES (2, 'TRUE');
-- INSERT INTO FLAG_REVIEW VALUES (3, 'FALSE');
-- INSERT INTO FLAG_REVIEW VALUES (4, 'TRUE');
-- INSERT INTO FLAG_REVIEW VALUES (5, 'FALSE');
-- INSERT INTO FLAG_REVIEW VALUES (6, 'TRUE');
-- INSERT INTO FLAG_REVIEW VALUES (7, 'TRUE');
-- INSERT INTO FLAG_REVIEW VALUES (8, 'FALSE');
-- INSERT INTO FLAG_REVIEW VALUES (9, 'TRUE');
-- INSERT INTO FLAG_REVIEW VALUES (10, 'FALSE');
-- COMMIT;

SELECT * FROM USER_FLAG;
SELECT * FROM FLAG_REVIEW;

-- KPMG Interview Question
-- CREATE TABLE K1 (
--     id NUMBER,
--     name VARCHAR2(50)
-- );

-- INSERT INTO K1 (id, name) VALUES (1, 'A');
-- INSERT INTO K1 (id, name) VALUES (1, 'A');
-- INSERT INTO K1 (id, name) VALUES (1, 'A');
-- INSERT INTO K1 (id, name) VALUES (2, 'B');
-- INSERT INTO K1 (id, name) VALUES (NULL, NULL);

-- COMMIT;

-- CREATE TABLE K2 (
--     id NUMBER,
--     name VARCHAR2(50)
-- );

-- INSERT INTO K2 (id, name) VALUES (1, 'A');
-- INSERT INTO K2 (id, name) VALUES (1, 'A');
-- INSERT INTO K2 (id, name) VALUES (NULL, NULL);
-- INSERT INTO K2 (id, name) VALUES (NULL, NULL);
-- INSERT INTO K2 (id, name) VALUES (3, 'C');

-- COMMIT;

SELECT * FROM K1;
SELECT * FROM K2;

Select count(*) from K1 inner join K2 on K1.ID = K2.ID;
Select count(*) from K1 left join K2 on K1.ID = K2.ID;
Select count(*) from K1 right join K2 on K1.ID = K2.ID;
Select count(*) from K1 full outer join K2 on K1.ID = K2.ID;

Select * from K1 inner join K2 on K1.ID = K2.ID;
Select * from K1 left join K2 on K1.ID = K2.ID;
Select * from K1 right join K2 on K1.ID = K2.ID;
Select * from K1 full outer join K2 on K1.ID = K2.ID;