-- Find the second highest salary without TOP, LIMIT, or RANK
SELECT * FROM EMP;

SELECT
    MAX(SAL) AS SECOND_MAX
FROM
    EMP
WHERE
    SAL < (SELECT MAX(SAL) FROM EMP);

-- Detect and delete duplicate rows

SELECT ROWID, D.* FROM DUPLICATES D;

SELECT ID, COUNT(*) AS CNT FROM DUPLICATES GROUP BY ID HAVING COUNT(*) > 1;
SELECT ID, MIN(ROWID) AS CNT FROM DUPLICATES GROUP BY ID;

DELETE FROM DUPLICATES D1
WHERE ROWID > (
    SELECT
        MIN(ROWID)
    FROM
        DUPLICATES D2
    WHERE D1.ID = D2.ID 
);

-- Query to find Winning Streak

SELECT * FROM STREAK;

WITH RES AS(
    SELECT
        ID,
        STATUS,
        ROW_NUMBER() OVER(ORDER BY ID) RN1,
        ROW_NUMBER() OVER(PARTITION BY STATUS ORDER BY ID) AS RN2,
        ROW_NUMBER() OVER(ORDER BY ID) - ROW_NUMBER() OVER(PARTITION BY STATUS ORDER BY ID) AS RN3
    FROM
        STREAK
)
SELECT
    MIN(ID) AS START_ID,
    MAX(ID) AS END_ID,
    COUNT(*) AS STREAK_LENGTH
FROM
    RES
WHERE STATUS = 'W'
GROUP BY RN3;