SELECT * FROM EMP ORDER BY SAL DESC;

SELECT
    E1.EMPNO AS EMPNO,
    E1.ENAME AS EMP_NAME,
    E1.JOB AS JOB,
    E1.MGR AS MANAGER_ID,
    E2.ENAME AS MANAGER_NAME
FROM
    EMP E1 LEFT JOIN EMP E2
    ON (E1.MGR = E2.EMPNO);

SELECT EMPNO, ENAME, MGR FROM EMP;

WITH TEMP(EMPNO, ENAME, MGR, LVL) AS (
    SELECT
        EMPNO,
        ENAME,
        MGR,
        1 AS LVL
    FROM
        EMP
    WHERE EMPNO = 7788
    UNION ALL
    SELECT
        E1.EMPNO,
        E1.ENAME,
        E1.MGR,
        E2.LVL + 1
    FROM
        EMP E1 INNER JOIN TEMP E2 ON E1.EMPNO = E2.MGR
) SELECT * FROM TEMP ORDER BY LVL DESC;

WITH EMP_HRC(EMPNO, ENAME, MGR, EMPLEVEL) AS (
    SELECT
        EMPNO,
        ENAME,
        MGR,
        1 AS EMPLEVEL
    FROM
        EMP WHERE MGR IS NULL
    UNION ALL
    SELECT
        E1.EMPNO,
        E1.ENAME,
        E1.MGR,
        E2.EMPLEVEL + 1
    FROM
        EMP E1 INNER JOIN EMP_HRC E2 ON E1.MGR = E2.EMPNO
) SELECT * FROM EMP_HRC;

SELECT
    EMPNO,
    ENAME,
    MGR,
    LEVEL
FROM
    EMP
    START WITH MGR IS NULL
    CONNECT BY PRIOR EMPNO = MGR
    ORDER BY LEVEL;

SELECT
    EMPNO,
    ENAME,
    JOB,
    DEPTNO,
    ROW_NUMBER() OVER(PARTITION BY DEPTNO ORDER BY EMPNO) AS RN,
    NTILE(3) OVER(PARTITION BY DEPTNO ORDER BY EMPNO) AS NT
FROM EMP;

-- CUMULATIVE SALARY AND CUMULATIVE PERCENTILE
WITH RES AS(
    SELECT
        EMPNO,
        ENAME,
        SAL,
        SUM(SAL) OVER(ORDER BY SAL) AS CUMULATIVE_SALARY,
        SUM(SAL) OVER() AS TOTAL_SAL,
        ROUND((SUM(SAL) OVER(ORDER BY SAL) / SUM(SAL) OVER()) * 100, 2) AS CUMULATIVE_SAL_PCT,
        NTILE(4) OVER(ORDER BY SAL) AS TOP_SAL
    FROM
        EMP
)
SELECT
    ENAME,
    SAL,
    CUMULATIVE_SALARY,
    CUMULATIVE_SAL_PCT,
    TOP_SAL
FROM
    RES
WHERE TOP_SAL = 1;

WITH RES AS(
    SELECT
        EMPNO,
        ENAME,
        SAL,
        ROW_NUMBER() OVER(ORDER BY SAL) AS RN
    FROM
        EMP
),
FINAL_RES AS (
    SELECT
        EMPNO,
        ENAME,
        SAL,
        SUM(SAL) OVER(ORDER BY RN) CUMULATIVE_SALARY,
        SUM(SAL) OVER() AS TOTAL_SAL
    FROM
        RES
)
SELECT
    EMPNO,
    ENAME,
    SAL,
    CUMULATIVE_SALARY,
    ROUND((CUMULATIVE_SALARY / TOTAL_SAL) * 100, 2) AS CUMULATIVE_SAL_PCT,
    TOTAL_SAL,
    NTILE(4) OVER(ORDER BY CUMULATIVE_SALARY) AS NT
FROM
    FINAL_RES;