-- Null is not a value its state
-- joins not get performed based on NULL values of a column

SELECT * FROM A1;
SELECT * FROM A2;

SELECT COUNT(*) FROM A2;
SELECT COUNT(1) FROM A2;

SELECT * FROM A1 WHERE ID IS NULL;

SELECT A1.*, 'INNER' FROM A1 INNER JOIN A2 ON A1.ID = A2.ID;

SELECT COUNT(*), 'INNER' FROM A1 INNER JOIN A2 ON A1.ID = A2.ID;
SELECT A1.ID, A1.NAME AS A1_NAME, A2.NAME AS A2_NAME, 'INNER' AS JOIN_TYPE FROM A1 INNER JOIN A2 ON A1.ID = A2.ID;

SELECT COUNT(*), 'LEFT' FROM A1 LEFT JOIN A2 ON A1.ID = A2.ID;
SELECT A1.ID, A1.NAME AS A1_NAME, A2.NAME AS A2_NAME, 'LEFT' AS JOIN_TYPE FROM A1 LEFT JOIN A2 ON A1.ID = A2.ID;

SELECT COUNT(*), 'RIGHT' FROM A1 RIGHT JOIN A2 ON A1.ID = A2.ID;
SELECT A2.ID, A1.NAME AS A1_NAME, A2.NAME AS A2_NAME, 'RIGHT' AS JOIN_TYPE FROM A1 RIGHT JOIN A2 ON A1.ID = A2.ID;

SELECT COUNT(*), 'FULL' FROM A1 FULL JOIN A2 ON A1.ID = A2.ID;
SELECT A1.ID, A1.NAME AS A1_NAME, A2.NAME AS A2_NAME, 'FULL' AS JOIN_TYPE FROM A1 FULL JOIN A2 ON A1.ID = A2.ID;

SELECT A2.ID, A2.NAME AS A2_NAME, 'LEFT ANTI' AS JOIN_TYPE
FROM A1 FULL JOIN A2 ON A1.ID = A2.ID WHERE A1.ID IS NUll AND A1.NAME IS NULL;

SELECT * FROM A1;

SELECT COUNT(*) FROM A1;
SELECT COUNT(1) FROM A1;

SELECT COUNT(ID) FROM A1;
SELECT COUNT(DISTINCT ID) FROM A1;
SELECT COUNT(ALL ID) FROM A1;

SELECT COUNT(NAME) FROM A1;
SELECT COUNT(DISTINCT NAME) FROM A1;
SELECT COUNT(ALL NAME) FROM A1;

SELECT * FROM A2;
SELECT COUNT(*) FROM A2;
SELECT COUNT(ID) FROM A2;

-- NULL is not a values its a state
SELECT * FROM A2 WHERE ID IS NULL;
SELECT * FROM A2 WHERE ID = NULL;

-- NULL does not take part in comparision

SELECT * FROM A3;
SELECT * FROM A4;

SELECT * FROM A3 INNER JOIN A4 ON A4.VAL = A3.VAL;
SELECT * FROM A3 LEFT JOIN A4 ON A4.VAL = A3.VAL;

-- 

SELECT * FROM CUST;
SELECT * FROM PROD;
SELECT * FROM ORD;

-- Total Purchases by each customers
WITH RES AS(
    SELECT
        CUST_ID,
        COUNT(*) AS CNT
    FROM
        ORD
    GROUP BY CUST_ID
)
SELECT
    CUST.CUST_ID,
    CUST.NAME,
    RES.CNT AS TOTAL_PURCHASES
FROM
    CUST
    INNER JOIN RES
    ON RES.CUST_ID = CUST.CUST_ID;

-- Query to get customers who bought anything
SELECT * FROM CUST WHERE CUST_ID IN (SELECT DISTINCT CUST_ID FROM ORD);
SELECT * FROM CUST WHERE EXISTS (SELECT 1 FROM ORD WHERE ORD.CUST_ID = CUST.CUST_ID) ORDER BY CUST.CUST_ID;

-- Query to get the customer who hasn't bought anything
SELECT * FROM CUST WHERE CUST_ID NOT IN (SELECT DISTINCT CUST_ID FROM ORD);
SELECT * FROM CUST WHERE NOT EXISTS (SELECT 1 FROM ORD WHERE ORD.CUST_ID = CUST.CUST_ID) ORDER BY CUST.CUST_ID;

-- SELECT
--     *
-- FROM CUST INNER JOIN ORD ON CUST.CUST_ID = ORD.CUST_ID

-- Query to get customers who has IPHONE & SAMSUNG, but not XIOMI
WITH RES AS(
    SELECT
        CUST_ID,
        SUM(CASE WHEN ORD.PROD_ID = 1 THEN 1 ELSE 0 END) AS IPHONE,
        SUM(CASE WHEN ORD.PROD_ID = 2 THEN 1 ELSE 0 END) AS SAMSUNG,
        SUM(CASE WHEN ORD.PROD_ID = 3 THEN 1 ELSE 0 END) AS XIOMI
    FROM
        ORD
    GROUP BY CUST_ID
)
SELECT
    *
FROM
    RES
WHERE
    IPHONE <> 0 AND SAMSUNG <> 0 AND XIOMI = 0;


-- Query to get missing values using recursive CTEs
SELECT * FROM TMP1;

WITH REC(N) AS(
    SELECT 1 FROM DUAL
    UNION ALL
    SELECT N + 1 FROM REC WHERE N < (SELECT MAX(ID) FROM TMP1)
),
RES AS(
    SELECT
        A.N AS ID_1,
        B.ID AS ID_2
    FROM
        REC A LEFT JOIN TMP1 B ON A.N = B.ID 
)
SELECT
    ID_1 AS ID
FROM RES
WHERE ID_2 IS NULL
ORDER BY ID_1;

-- Query to find out flags reviewed by youtube for the videos
-- that most no of user flags

SELECT * FROM USER_FLAG;
SELECT * FROM FLAG_REVIEW;

-- KPMG Interview Question

SELECT * FROM K1;
SELECT * FROM K2;

Select count(*) from K1 inner join K2 on K1.ID = K2.ID;
Select count(*) from K1 left join K2 on K1.ID = K2.ID;
Select count(*) from K1 right join K2 on K1.ID = K2.ID;
Select count(*) from K1 full outer join K2 on K1.ID = K2.ID;

Select * from K1 inner join K2 on K1.ID = K2.ID;
Select * from K1 left join K2 on K1.ID = K2.ID;
Select * from K1 right join K2 on K1.ID = K2.ID;
Select * from K1 full outer join K2 on K1.ID = K2.ID;