-- VANGUARD QUESTION 1

-- CREATE TABLE SALARY (
--     TENURE NUMBER,
--     SALARY NUMBER
-- );

-- INSERT INTO SALARY VALUES(3, 6000);
-- INSERT INTO SALARY VALUES(3, 3000);
-- INSERT INTO SALARY VALUES(2, 5000);
-- INSERT INTO SALARY VALUES(2, 6000);
-- INSERT INTO SALARY VALUES(2, 6000);
-- INSERT INTO SALARY VALUES(2, 6000);
-- INSERT INTO SALARY VALUES(10, 70000);
-- INSERT INTO SALARY VALUES(5, 1000);
-- INSERT INTO SALARY VALUES(6, 50000);
-- COMMIT;

SELECT * FROM SALARY ORDER BY TENURE;

WITH SAL AS (
    SELECT
        TENURE,
        SALARY,
        NTH_VALUE(SALARY, 2) OVER(PARTITION BY TENURE ORDER BY SALARY DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS VAL_0,
        NTH_VALUE(SALARY, 2) OVER(PARTITION BY TENURE ORDER BY SALARY DESC) AS VAL
    FROM SALARY
) SELECT * FROM SAL WHERE VAL IS NOT NULL;

-- Query to get the 2nd lowest salary for each tenure
WITH SAL AS (
    SELECT
        TENURE,
        SALARY,
        DENSE_RANK() OVER(PARTITION BY TENURE ORDER BY SALARY ASC) AS DN
    FROM
        SALARY
)
SELECT TENURE, SALARY, DN FROM SAL WHERE DN = 2;

-- Query to get the 2nd highest salary for each tenure, if not available get the highest salary
WITH SAL AS (
    SELECT
        TENURE,
        SALARY,
        DENSE_RANK() OVER(PARTITION BY TENURE ORDER BY SALARY DESC) AS DN
    FROM SALARY
), SECOND AS(
    SELECT * FROM SAL WHERE DN = 2
), FIRST AS (
    SELECT
        *
    FROM
        SAL
    WHERE
        TENURE NOT IN (SELECT DISTINCT TENURE FROM SECOND) AND
        DN = 1
), RES AS(
    SELECT TENURE, SALARY FROM FIRST
    UNION
    SELECT TENURE, SALARY FROM SECOND
) SELECT * FROM RES ORDER BY TENURE;


-- VANGUARD QUESTION 2
-- CREATE TABLE FUND_ALLOCATION (
--     FUNDID NUMBER,
--     ALLOCATION_TYPE VARCHAR2(50),
--     ALLOCATION_PERCENTAGE NUMBER(5,2)
-- );
-- INSERT INTO FUND_ALLOCATION VALUES (2342, 'BOND', 0.2);
-- INSERT INTO FUND_ALLOCATION VALUES (2342, 'CASH', 0.7);
-- INSERT INTO FUND_ALLOCATION VALUES (2342, 'CTSK', 0.1);

-- CREATE TABLE FUND(
--     PARTID NUMBER,
--     FUNDID NUMBER,
--     BALANCE NUMBER
-- );
-- INSERT INTO FUND VALUES (34546778, 2342, 5000);
-- INSERT INTO FUND VALUES (11254678, 2342, 50000);
-- COMMIT;

SELECT * FROM FUND_ALLOCATION;
SELECT * FROM FUND;

-- Method 1: Query to fund allocation using multiple joins
SELECT
    F.PARTID,
    F.FUNDID,
    F.BALANCE,
    F.BALANCE * A1.ALLOCATION_PERCENTAGE AS BOND,
    F.BALANCE * A2.ALLOCATION_PERCENTAGE AS CASH,
    F.BALANCE * A3.ALLOCATION_PERCENTAGE AS CTSK
FROM
    FUND F
    LEFT JOIN FUND_ALLOCATION A1 ON F.FUNDID = A1.FUNDID AND A1.ALLOCATION_TYPE = 'BOND'
    LEFT JOIN FUND_ALLOCATION A2 ON F.FUNDID = A2.FUNDID AND A2.ALLOCATION_TYPE = 'CASH'
    LEFT JOIN FUND_ALLOCATION A3 ON F.FUNDID = A3.FUNDID AND A3.ALLOCATION_TYPE = 'CTSK';

-- Method 2: Query to fund allocation using conditional aggregation
SELECT
    F.PARTID,
    F.FUNDID,
    F.BALANCE,
    ROUND(SUM(CASE WHEN A.ALLOCATION_TYPE = 'BOND' THEN A.ALLOCATION_PERCENTAGE * F.BALANCE ELSE 0 END), 2) AS BOND,
    ROUND(SUM(CASE WHEN A.ALLOCATION_TYPE = 'CASH' THEN A.ALLOCATION_PERCENTAGE * F.BALANCE ELSE 0 END), 2) AS CASH,
    ROUND(SUM(CASE WHEN A.ALLOCATION_TYPE = 'CTSK' THEN A.ALLOCATION_PERCENTAGE * F.BALANCE ELSE 0 END), 2) AS CTSK
FROM
    FUND F
    LEFT JOIN FUND_ALLOCATION A ON F.FUNDID = A.FUNDID
GROUP BY F.PARTID, F.FUNDID, F.BALANCE;

-- VANGUARD QUESTION 3
-- CREATE TABLE STOCK_PRICES (
--     TRADE_DATE DATE,
--     STOCK VARCHAR2(10),
--     OPEN_PRICE NUMBER(10,2),
--     DAYS_HIGH NUMBER(10,2),
--     DAYS_LOW NUMBER(10,2),
--     CLOSE_PRICE NUMBER(10,2)
-- );

-- INSERT INTO STOCK_PRICES VALUES (TO_DATE('2025-01-20', 'YYYY-MM-DD'), 'AAPL', 230.4, 232.65, 228.5, 232.1);
-- INSERT INTO STOCK_PRICES VALUES (TO_DATE('2025-01-21', 'YYYY-MM-DD'), 'AAPL', 234.2, 247.5, 234.2, 247.5);
-- INSERT INTO STOCK_PRICES VALUES (TO_DATE('2025-01-22', 'YYYY-MM-DD'), 'AAPL', 245.4, 248.5, 243.15, 248.1);
-- INSERT INTO STOCK_PRICES VALUES (TO_DATE('2025-01-23', 'YYYY-MM-DD'), 'AAPL', 247.10, 262.6, 245.8, 260.9);
-- INSERT INTO STOCK_PRICES VALUES (TO_DATE('2025-01-20', 'YYYY-MM-DD'), 'AMD', 110.4, 118.85, 110.3, 116.6);
-- INSERT INTO STOCK_PRICES VALUES (TO_DATE('2025-01-21', 'YYYY-MM-DD'), 'AMD', 115.5, 117.25, 113.5, 117.25);
-- INSERT INTO STOCK_PRICES VALUES (TO_DATE('2025-01-22', 'YYYY-MM-DD'), 'AMD', 120.2, 130.5, 120.15, 130.5);
-- INSERT INTO STOCK_PRICES VALUES (TO_DATE('2025-01-23', 'YYYY-MM-DD'), 'AMD', 130.1, 131.5, 117.25, 119.0);
-- COMMIT;

SELECT * FROM STOCK_PRICES;

-- Method 1: Query to get count of days stock price increased by more than 5%
WITH RES AS(
    SELECT
        STOCK,
        (CLOSE_PRICE - OPEN_PRICE) / OPEN_PRICE AS PER
    FROM STOCK_PRICES
)
SELECT
    STOCK,
    COUNT(*) CNT
FROM
    RES
WHERE PER > 0.05
GROUP BY STOCK;

-- Method 2: Query to get count of days stock price increased by more than 5%
SELECT
    STOCK,
    COUNT(*) AS CNT
FROM
    STOCK_PRICES
WHERE
    ((CLOSE_PRICE - OPEN_PRICE) / OPEN_PRICE) > 0.05
GROUP BY STOCK;

-- VANGUARD QUESTION 4
SELECT * FROM SALES;

-- Method 1: Query to get total sales by department and percentage contribution
SELECT
    DISTINCT DEPARTMENT_ID,
    SUM(TOTAL_SALES) OVER(PARTITION BY DEPARTMENT_ID) AS DEPARTMENT_TOTAL_SALES,
    ROUND((SUM(TOTAL_SALES) OVER(PARTITION BY DEPARTMENT_ID) / SUM(TOTAL_SALES) OVER()) * 100, 2) AS SALES_PERCENTAGE_BY_DEPARTMENT
FROM SALES;

-- Method 2: Query to get total sales by department and percentage contribution
SELECT
    SALES_ID, EMPLOYEE_NAME, DEPARTMENT_ID, TOTAL_SALES,
    ROUND((TOTAL_SALES / SUM(TOTAL_SALES) OVER()) * 100, 2) AS PERCENTAGE
FROM SALES;

-- VANGUARD QUESTION 5
SELECT * FROM SALES;

SELECT
    SALES_ID,
    TOTAL_SALES,
    LAG(TOTAL_SALES) OVER(ORDER BY SALES_ID) PREV_SALES,
    LEAD(TOTAL_SALES) OVER(ORDER BY SALES_ID) NEXT_SALES,
    LAG(TOTAL_SALES, 2) OVER(ORDER BY SALES_ID) PREV_2_SALES,
    LEAD(TOTAL_SALES, 2) OVER(ORDER BY SALES_ID) NEXT_2_SALES
FROM SALES;