# Set everything to be logged at the WARN level
log4j.rootCategory=WARN, console

# Settings to get more verbose logging for specific classes
log4j.logger.org.apache.spark.sql=DEBUG
log4j.logger.org.apache.hadoop=DEBUG
log4j.logger.org.apache.parquet=DEBUG

# console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.err
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n