rootLogger.level = error

logger.spark.name = org.apache.spark
logger.spark.level = error

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = error

logger.ivy.name = org.apache.ivy
logger.ivy.level = error

logger.jetty.name = org.eclipse.jetty
logger.jetty.level = error

logger.parquet.name = org.apache.parquet
logger.parquet.level = error