name: Artifacts - Deploy Website

# This will create a build folder with the production build of the website

on:
    # push:
    #     branches:
    #         - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Get the code
          uses: actions/checkout@v3
        
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: '18'

        - name: Cache dependencies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

        - name: Install dependencies
          working-directory: frontend/github-actions-first
          run:
            npm ci

        - name: Run tests
          working-directory: frontend/github-actions-first
          run: |
            npm run test
    
    build:
        needs: test
        runs-on: ubuntu-latest
        outputs:
            script-file: ${{ steps.publish-js-filename.outputs.script-file }}
        steps:
        - name: Get the code
          uses: actions/checkout@v3
        
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: '18'
        
        - name: Cache dependencies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

        - name: Install dependencies
          working-directory: frontend/github-actions-first
          run:
            npm ci

        - name: Build Project
          working-directory: frontend/github-actions-first
          run: |
            npm run build

        - name: Publish JS filename
          id: publish-js-filename
          working-directory: frontend/github-actions-first
          run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
          # run: find dist/assets/*.js -type f -execdir echo '::set-output name=script-file::{}' ';' # Not supported
        
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: dist-files
            path: |
                frontend/github-actions-first/dist
                frontend/github-actions-first/package.json
    
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifact
              uses: actions/download-artifact@v4
              with:
                name: dist-files
            
            - name: List files
              run: ls
            
            - name: Output filename
              run: echo "${{ needs.build.outputs.script-file }}"
            
            - name: Deploy
              run: echo "Deploying the website"
