name: Environment Variables

# This will create a build folder with the production build of the website

on:
    # push:
    #     branches:
    #         - main
    workflow_dispatch:

env:
    MONGODB_DB_NAME: gha-demo
jobs:
    test:
        environment: SAT
        env:
            MONGODB_CLUSTER_ADDRESS: cluster0.5ibi6xj.mongodb.net
            MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
            MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
            PORT: 8080
        
        runs-on: ubuntu-latest
        steps:
        - name: Get the code
          uses: actions/checkout@v3

        - name: Cache dependencies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

        - name: Install dependencies
          working-directory: frontend/github-actions-second
          run:
            npm ci
        
        - name: Run server
          working-directory: frontend/github-actions-second
          run: npm start & npx wait-on http://127.0.0.1:${{ env.PORT }}

        - name: Run tests
          working-directory: frontend/github-actions-second
          run: |
            npm run test
        
        - name: Output information
          run: |
            echo "MONODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
    
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Output information
              run: |
                echo "MONODB_USERNAME: ${{ env.MONGODB_USERNAME }}"