name: Execution Flow

on:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            
            - name: Cache Dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install Dependencies
              working-directory: frontend/github-actions-third
              run: npm ci
            
            - name: Lint Code
              working-directory: frontend/github-actions-third
              run: npm run lint

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            
            - name: Cache Dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            
            - name: Install Dependencies
              working-directory: frontend/github-actions-third
              run: npm ci

            - name: Test Code
              working-directory: frontend/github-actions-third
              run: npm run test

            - name: Upload Test Results
              uses: actions/upload-artifact@v4
              with:
                name: test-report
                path: frontend/github-actions-third/test.json

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            
            - name: Cache Dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install Dependencies
              working-directory: frontend/github-actions-third
              run: npm ci

            - name: Build Code
              working-directory: frontend/github-actions-third
              run: npm run build

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dist-files
                path: |
                    frontend/github-actions-third/dist

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            
            - name: Download Build Artifacts
              uses: actions/download-artifact@v4
              with:
                name: dist-files

            - name: Output contents
              run: ls -la
            
            - name: Deploy Code
              run: echo "Deploying code..."