name: 009 - Resuable Workflow

on:
    workflow_call:
        inputs:
            artifact-name:
                description: 'Name of the artifact to download'
                default: 'dist-files'
                required: true
                type: string
        
        outputs:
            result:
                description: 'Output result from the reusable workflow'
                value: ${{ jobs.deploy.outputs.outcome }}

        secrets:
            some-secret:
                description: 'A secret that can be used in the reusable workflow'
                required: false

jobs:
    deploy:
        outputs:
            outcome: ${{ steps.set-output.outputs.set-result }}
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact-name }}

            - name: Output contents
              run: |
                ls -la
                echo ${{ secrets.some-secret }}

            - name: Run deployment script
              run: echo "Deploying application..."
            
            - name: Set Output
              id: set-output
              run: echo "set-result=Deployment Successful" >> $GITHUB_OUTPUT