name: Deploy CloudFormation Stack

on:
  workflow_dispatch:
    inputs:
      region:
        description: Select AWS Region
        required: true
        type: choice
        options:
          - us-east-1
          - us-west-2
          - ap-south-1
          - eu-west-1

      stack_name:
        description: Select Stack Name
        required: true
        type: choice
        options:
          - iceberg-table

permissions:
  id-token: write
  contents: read

jobs:
  deploy-cft:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ github.event.inputs.region }}
      STACK_NAME: ${{ github.event.inputs.stack_name }}
      TEMPLATE_FILE: ${{ github.event.inputs.stack_name }}/cloudformation/cft.yml

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::741448939728:role/GITHUB_OIDC_ROLE
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}


      - name: Validate CloudFormation Template
        run: |
          ls -la
          pwd
          aws cloudformation validate-template \
            --template-body file://${{ env.TEMPLATE_FILE }}

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name ${{ env.STACK_NAME }} \
            --template-file ${{ env.TEMPLATE_FILE }} \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{ env.AWS_REGION }}

      - name: Show Stack Outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name ${{ env.STACK_NAME }} \
            --query "Stacks[0].Outputs"